// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var AvcodecAllocContext3 func(unsafe.Pointer) unsafe.Pointer

var AvcodecFreeContext func(unsafe.Pointer)

var AvcodecParametersFromContext func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecParametersToContext func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecOpen2 func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) int32

var AvcodecSendPacket func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecReceiveFrame func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecSendFrame func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecReceivePacket func(unsafe.Pointer, unsafe.Pointer) int32

var AvcodecFlushBuffers func(unsafe.Pointer)

var AvcodecIsOpen func(unsafe.Pointer) int32

func RegisterAvcodec(handle uintptr) {
	purego.RegisterLibFunc(&AvcodecAllocContext3, handle, "avcodec_alloc_context3")
	purego.RegisterLibFunc(&AvcodecFreeContext, handle, "avcodec_free_context")
	purego.RegisterLibFunc(&AvcodecParametersFromContext, handle, "avcodec_parameters_from_context")
	purego.RegisterLibFunc(&AvcodecParametersToContext, handle, "avcodec_parameters_to_context")
	purego.RegisterLibFunc(&AvcodecOpen2, handle, "avcodec_open2")
	purego.RegisterLibFunc(&AvcodecSendPacket, handle, "avcodec_send_packet")
	purego.RegisterLibFunc(&AvcodecReceiveFrame, handle, "avcodec_receive_frame")
	purego.RegisterLibFunc(&AvcodecSendFrame, handle, "avcodec_send_frame")
	purego.RegisterLibFunc(&AvcodecReceivePacket, handle, "avcodec_receive_packet")
	purego.RegisterLibFunc(&AvcodecFlushBuffers, handle, "avcodec_flush_buffers")
	purego.RegisterLibFunc(&AvcodecIsOpen, handle, "avcodec_is_open")
}
