// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"structs"
	"unsafe"

	"github.com/ebitengine/purego"
)

type AVOutputFormat struct {
	_          structs.HostLayout
	Name       *byte
	LongName   *byte
	MimeType   *byte
	Extensions *byte
	Flags      int32
	CodecTag   unsafe.Pointer
	PrivClass  unsafe.Pointer
}

type AVInputFormat struct {
	_          structs.HostLayout
	Name       *byte
	LongName   *byte
	Flags      int32
	Extensions *byte
	CodecTag   unsafe.Pointer
	PrivClass  unsafe.Pointer
	MimeType   *byte
}

type AVStream struct {
	_                 structs.HostLayout
	AvClass           unsafe.Pointer
	Index             int32
	ID                int32
	Codecpar          unsafe.Pointer
	PrivData          unsafe.Pointer
	TimeBase          AVRational
	StartTime         int64
	Duration          int64
	NbFrames          int64
	Disposition       int32
	SampleAspectRatio AVRational
	Metadata          unsafe.Pointer
	AvgFrameRate      AVRational
	AttachedPic       uintptr
	EventFlags        int32
	RFrameRate        AVRational
	PTSWrapBits       int32
}

var AvformatVersion func() uint32

var AvformatAllocContext func() unsafe.Pointer

var AvformatFreeContext func(unsafe.Pointer)

var AvformatNewStream func(unsafe.Pointer, unsafe.Pointer) unsafe.Pointer

var AvformatAllocOutputContext2 func(unsafe.Pointer, unsafe.Pointer, *byte, *byte) int32

var AvformatOpenInput func(unsafe.Pointer, *byte, unsafe.Pointer, unsafe.Pointer) int32

var AvformatFindStreamInfo func(unsafe.Pointer, unsafe.Pointer) int32

var AVFindBestStream func(unsafe.Pointer, int32, int32, int32, unsafe.Pointer, int32) int32

var AVReadFrame func(unsafe.Pointer, unsafe.Pointer) int32

var AvformatCloseInput func(unsafe.Pointer)

var AvformatWriteHeader func(unsafe.Pointer, unsafe.Pointer) int32

var AVInterleavedWriteFrame func(unsafe.Pointer, unsafe.Pointer) int32

var AVWriteTrailer func(unsafe.Pointer) int32

func RegisterAvformat(handle uintptr) {
	purego.RegisterLibFunc(&AvformatVersion, handle, "avformat_version")
	purego.RegisterLibFunc(&AvformatAllocContext, handle, "avformat_alloc_context")
	purego.RegisterLibFunc(&AvformatFreeContext, handle, "avformat_free_context")
	purego.RegisterLibFunc(&AvformatNewStream, handle, "avformat_new_stream")
	purego.RegisterLibFunc(&AvformatAllocOutputContext2, handle, "avformat_alloc_output_context2")
	purego.RegisterLibFunc(&AvformatOpenInput, handle, "avformat_open_input")
	purego.RegisterLibFunc(&AvformatFindStreamInfo, handle, "avformat_find_stream_info")
	purego.RegisterLibFunc(&AVFindBestStream, handle, "av_find_best_stream")
	purego.RegisterLibFunc(&AVReadFrame, handle, "av_read_frame")
	purego.RegisterLibFunc(&AvformatCloseInput, handle, "avformat_close_input")
	purego.RegisterLibFunc(&AvformatWriteHeader, handle, "avformat_write_header")
	purego.RegisterLibFunc(&AVInterleavedWriteFrame, handle, "av_interleaved_write_frame")
	purego.RegisterLibFunc(&AVWriteTrailer, handle, "av_write_trailer")
}
