// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var AvioOpen func(unsafe.Pointer, *byte, int32) int32

var AvioClosep func(unsafe.Pointer) int32

func RegisterAvio(handle uintptr) {
	purego.RegisterLibFunc(&AvioOpen, handle, "avio_open")
	purego.RegisterLibFunc(&AvioClosep, handle, "avio_closep")
}
