// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

type MediaType int32

var AvutilVersion func() uint32

func RegisterAvutil(handle uintptr) {
	purego.RegisterLibFunc(&AvutilVersion, handle, "avutil_version")
}
