// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var AvcodecFindDecoder func(int32) unsafe.Pointer

var AvcodecFindDecoderByName func(*byte) unsafe.Pointer

var AvcodecFindEncoder func(int32) unsafe.Pointer

var AvcodecFindEncoderByName func(*byte) unsafe.Pointer

func RegisterCodec(handle uintptr) {
	purego.RegisterLibFunc(&AvcodecFindDecoder, handle, "avcodec_find_decoder")
	purego.RegisterLibFunc(&AvcodecFindDecoderByName, handle, "avcodec_find_decoder_by_name")
	purego.RegisterLibFunc(&AvcodecFindEncoder, handle, "avcodec_find_encoder")
	purego.RegisterLibFunc(&AvcodecFindEncoderByName, handle, "avcodec_find_encoder_by_name")
}
