// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"structs"
	"unsafe"

	"github.com/ebitengine/purego"
)

type AVDictionaryEntry struct {
	_     structs.HostLayout
	Key   *byte
	Value *byte
}

var AVDictGet func(unsafe.Pointer, *byte, unsafe.Pointer, int32) unsafe.Pointer

var AVDictCount func(unsafe.Pointer) int32

var AVDictSet func(unsafe.Pointer, *byte, *byte, int32) int32

var AVDictFree func(unsafe.Pointer)

func RegisterDict(handle uintptr) {
	purego.RegisterLibFunc(&AVDictGet, handle, "av_dict_get")
	purego.RegisterLibFunc(&AVDictCount, handle, "av_dict_count")
	purego.RegisterLibFunc(&AVDictSet, handle, "av_dict_set")
	purego.RegisterLibFunc(&AVDictFree, handle, "av_dict_free")
}
