// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

var AVStrerror func(int32, *byte, uintptr) int32

func RegisterError(handle uintptr) {
	purego.RegisterLibFunc(&AVStrerror, handle, "av_strerror")
}
