// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

type FrameSideDataType int32

var AVFrameAlloc func() unsafe.Pointer

var AVFrameFree func(unsafe.Pointer)

var AVFrameRef func(unsafe.Pointer, unsafe.Pointer) int32

var AVFrameClone func(unsafe.Pointer) unsafe.Pointer

var AVFrameUnref func(unsafe.Pointer)

var AVFrameGetBuffer func(unsafe.Pointer, int32) int32

var AVFrameIsWritable func(unsafe.Pointer) int32

var AVFrameMakeWritable func(unsafe.Pointer) int32

func RegisterFrame(handle uintptr) {
	purego.RegisterLibFunc(&AVFrameAlloc, handle, "av_frame_alloc")
	purego.RegisterLibFunc(&AVFrameFree, handle, "av_frame_free")
	purego.RegisterLibFunc(&AVFrameRef, handle, "av_frame_ref")
	purego.RegisterLibFunc(&AVFrameClone, handle, "av_frame_clone")
	purego.RegisterLibFunc(&AVFrameUnref, handle, "av_frame_unref")
	purego.RegisterLibFunc(&AVFrameGetBuffer, handle, "av_frame_get_buffer")
	purego.RegisterLibFunc(&AVFrameIsWritable, handle, "av_frame_is_writable")
	purego.RegisterLibFunc(&AVFrameMakeWritable, handle, "av_frame_make_writable")
}
