// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

var AVImageGetBufferSize func(int32, int32, int32, int32) int32

func RegisterImgutils(handle uintptr) {
	purego.RegisterLibFunc(&AVImageGetBufferSize, handle, "av_image_get_buffer_size")
}
