// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

var AVLogGetLevel func() int32

var AVLogSetLevel func(int32)

func RegisterLog(handle uintptr) {
	purego.RegisterLibFunc(&AVLogGetLevel, handle, "av_log_get_level")
	purego.RegisterLibFunc(&AVLogSetLevel, handle, "av_log_set_level")
}
