// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

var AVRescaleQ func(int64, AVRational, AVRational) int64

var AVRescaleQRnd func(int64, AVRational, AVRational, int32) int64

func RegisterMathematics(handle uintptr) {
	purego.RegisterLibFunc(&AVRescaleQ, handle, "av_rescale_q")
	purego.RegisterLibFunc(&AVRescaleQRnd, handle, "av_rescale_q_rnd")
}
