// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var AVPacketAlloc func() unsafe.Pointer

var AVPacketFree func(unsafe.Pointer)

var AVPacketRef func(unsafe.Pointer, unsafe.Pointer) int32

var AVPacketUnref func(unsafe.Pointer)

var AVPacketRescaleTs func(unsafe.Pointer, AVRational, AVRational)

func RegisterPacket(handle uintptr) {
	purego.RegisterLibFunc(&AVPacketAlloc, handle, "av_packet_alloc")
	purego.RegisterLibFunc(&AVPacketFree, handle, "av_packet_free")
	purego.RegisterLibFunc(&AVPacketRef, handle, "av_packet_ref")
	purego.RegisterLibFunc(&AVPacketUnref, handle, "av_packet_unref")
	purego.RegisterLibFunc(&AVPacketRescaleTs, handle, "av_packet_rescale_ts")
}
