// Code generated by ffmpeggen. DO NOT EDIT.

package raw

// Handles holds all FFmpeg shared library handles.
type Handles struct {
	Avutil     uintptr
	Avcodec    uintptr
	Avformat   uintptr
	Swscale    uintptr
	Swresample uintptr
}

// Register loads all FFmpeg C API symbols from the shared libraries.
func Register(h Handles) {
	RegisterAvcodec(h.Avcodec)
	RegisterAvformat(h.Avformat)
	RegisterAvio(h.Avformat)
	RegisterAvutil(h.Avutil)
	RegisterCodec(h.Avcodec)
	RegisterDict(h.Avutil)
	RegisterError(h.Avutil)
	RegisterFrame(h.Avutil)
	RegisterImgutils(h.Avutil)
	RegisterLog(h.Avutil)
	RegisterMathematics(h.Avutil)
	RegisterPacket(h.Avcodec)
	RegisterSamplefmt(h.Avutil)
	RegisterSwresample(h.Swresample)
	RegisterSwscale(h.Swscale)
}
