// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"github.com/ebitengine/purego"
)

type SampleFormat int32

var AVGetSampleFmtName func(int32) *byte

var AVGetBytesPerSample func(int32) int32

var AVSampleFmtIsPlanar func(int32) int32

func RegisterSamplefmt(handle uintptr) {
	purego.RegisterLibFunc(&AVGetSampleFmtName, handle, "av_get_sample_fmt_name")
	purego.RegisterLibFunc(&AVGetBytesPerSample, handle, "av_get_bytes_per_sample")
	purego.RegisterLibFunc(&AVSampleFmtIsPlanar, handle, "av_sample_fmt_is_planar")
}
