// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var SWRAlloc func() unsafe.Pointer

var SWRInit func(unsafe.Pointer) int32

var SWRFree func(unsafe.Pointer)

var SWRConvert func(unsafe.Pointer, unsafe.Pointer, int32, unsafe.Pointer, int32) int32

var SwresampleVersion func() uint32

func RegisterSwresample(handle uintptr) {
	purego.RegisterLibFunc(&SWRAlloc, handle, "swr_alloc")
	purego.RegisterLibFunc(&SWRInit, handle, "swr_init")
	purego.RegisterLibFunc(&SWRFree, handle, "swr_free")
	purego.RegisterLibFunc(&SWRConvert, handle, "swr_convert")
	purego.RegisterLibFunc(&SwresampleVersion, handle, "swresample_version")
}
