// Code generated by ffmpeggen. DO NOT EDIT.

package raw

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

var SwscaleVersion func() uint32

var SWSFreeContext func(unsafe.Pointer)

var SWSGetContext func(int32, int32, int32, int32, int32, int32, int32, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) unsafe.Pointer

var SWSScale func(unsafe.Pointer, unsafe.Pointer, int32, int32, int32, unsafe.Pointer, int32) int32

func RegisterSwscale(handle uintptr) {
	purego.RegisterLibFunc(&SwscaleVersion, handle, "swscale_version")
	purego.RegisterLibFunc(&SWSFreeContext, handle, "sws_freeContext")
	purego.RegisterLibFunc(&SWSGetContext, handle, "sws_getContext")
	purego.RegisterLibFunc(&SWSScale, handle, "sws_scale")
}
