// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockFilterGraph is a test mock for FilterGraph.
type MockFilterGraph struct {
	FreeFunc func()
	PtrFunc  func() unsafe.Pointer
}

func (mock *MockFilterGraph) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockFilterGraph) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
