// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockCodecContext is a test mock for CodecContext.
type MockCodecContext struct {
	CodecTypeFunc       func() int32
	CodecIDFunc         func() int32
	TimeBaseFunc        func() AVRational
	SetTimeBaseFunc     func(v AVRational)
	WidthFunc           func() int32
	SetWidthFunc        func(v int32)
	HeightFunc          func() int32
	SetHeightFunc       func(v int32)
	PixelFormatFunc     func() int32
	SetPixelFormatFunc  func(v int32)
	SampleRateFunc      func() int32
	SetSampleRateFunc   func(v int32)
	SampleFormatFunc    func() int32
	SetSampleFormatFunc func(v int32)
	HWDeviceCtxFunc     func() unsafe.Pointer
	SetHWDeviceCtxFunc  func(v unsafe.Pointer)
	HWFramesCtxFunc     func() unsafe.Pointer
	SetHWFramesCtxFunc  func(v unsafe.Pointer)
	FreeFunc            func()
	PtrFunc             func() unsafe.Pointer
}

func (mock *MockCodecContext) CodecType() int32 {
	if mock.CodecTypeFunc != nil {
		return mock.CodecTypeFunc()
	}
	var zero int32
	return zero
}
func (mock *MockCodecContext) CodecID() int32 {
	if mock.CodecIDFunc != nil {
		return mock.CodecIDFunc()
	}
	var zero int32
	return zero
}
func (mock *MockCodecContext) TimeBase() AVRational {
	if mock.TimeBaseFunc != nil {
		return mock.TimeBaseFunc()
	}
	var zero AVRational
	return zero
}

func (mock *MockCodecContext) SetTimeBase(v AVRational) {
	if mock.SetTimeBaseFunc != nil {
		mock.SetTimeBaseFunc(v)
	}
}
func (mock *MockCodecContext) Width() int32 {
	if mock.WidthFunc != nil {
		return mock.WidthFunc()
	}
	var zero int32
	return zero
}

func (mock *MockCodecContext) SetWidth(v int32) {
	if mock.SetWidthFunc != nil {
		mock.SetWidthFunc(v)
	}
}
func (mock *MockCodecContext) Height() int32 {
	if mock.HeightFunc != nil {
		return mock.HeightFunc()
	}
	var zero int32
	return zero
}

func (mock *MockCodecContext) SetHeight(v int32) {
	if mock.SetHeightFunc != nil {
		mock.SetHeightFunc(v)
	}
}
func (mock *MockCodecContext) PixelFormat() int32 {
	if mock.PixelFormatFunc != nil {
		return mock.PixelFormatFunc()
	}
	var zero int32
	return zero
}

func (mock *MockCodecContext) SetPixelFormat(v int32) {
	if mock.SetPixelFormatFunc != nil {
		mock.SetPixelFormatFunc(v)
	}
}
func (mock *MockCodecContext) SampleRate() int32 {
	if mock.SampleRateFunc != nil {
		return mock.SampleRateFunc()
	}
	var zero int32
	return zero
}

func (mock *MockCodecContext) SetSampleRate(v int32) {
	if mock.SetSampleRateFunc != nil {
		mock.SetSampleRateFunc(v)
	}
}
func (mock *MockCodecContext) SampleFormat() int32 {
	if mock.SampleFormatFunc != nil {
		return mock.SampleFormatFunc()
	}
	var zero int32
	return zero
}

func (mock *MockCodecContext) SetSampleFormat(v int32) {
	if mock.SetSampleFormatFunc != nil {
		mock.SetSampleFormatFunc(v)
	}
}
func (mock *MockCodecContext) HWDeviceCtx() unsafe.Pointer {
	if mock.HWDeviceCtxFunc != nil {
		return mock.HWDeviceCtxFunc()
	}
	var zero unsafe.Pointer
	return zero
}

func (mock *MockCodecContext) SetHWDeviceCtx(v unsafe.Pointer) {
	if mock.SetHWDeviceCtxFunc != nil {
		mock.SetHWDeviceCtxFunc(v)
	}
}
func (mock *MockCodecContext) HWFramesCtx() unsafe.Pointer {
	if mock.HWFramesCtxFunc != nil {
		return mock.HWFramesCtxFunc()
	}
	var zero unsafe.Pointer
	return zero
}

func (mock *MockCodecContext) SetHWFramesCtx(v unsafe.Pointer) {
	if mock.SetHWFramesCtxFunc != nil {
		mock.SetHWFramesCtxFunc(v)
	}
}

func (mock *MockCodecContext) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockCodecContext) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
