// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockDictionary is a test mock for Dictionary.
type MockDictionary struct {
	FreeFunc func()
	PtrFunc  func() unsafe.Pointer
}

func (mock *MockDictionary) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockDictionary) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
