// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockDictionary is a test mock for Dictionary.
type MockDictionary struct {
	GetFunc     func(unsafe.Pointer, *byte, unsafe.Pointer, int32) unsafe.Pointer
	SetFunc     func(unsafe.Pointer, *byte, *byte, int32) int32
	FreePtrFunc func(unsafe.Pointer)
	CountFunc   func(unsafe.Pointer) int32
	FreeFunc    func()
	PtrFunc     func() unsafe.Pointer
}

func (mock *MockDictionary) Get(m unsafe.Pointer, key *byte, prev unsafe.Pointer, flags int32) unsafe.Pointer {
	if mock.GetFunc != nil {
		return mock.GetFunc(m, key, prev, flags)
	}
	var zero unsafe.Pointer
	return zero
}

func (mock *MockDictionary) Set(pm unsafe.Pointer, key *byte, value *byte, flags int32) int32 {
	if mock.SetFunc != nil {
		return mock.SetFunc(pm, key, value, flags)
	}
	var zero int32
	return zero
}

func (mock *MockDictionary) FreePtr(m unsafe.Pointer) {
	if mock.FreePtrFunc != nil {
		mock.FreePtrFunc(m)
		return
	}
}

func (mock *MockDictionary) Count(m unsafe.Pointer) int32 {
	if mock.CountFunc != nil {
		return mock.CountFunc(m)
	}
	var zero int32
	return zero
}

func (mock *MockDictionary) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockDictionary) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
