// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockFormatContext is a test mock for FormatContext.
type MockFormatContext struct {
	NbStreamsFunc  func() uint32
	StreamsPtrFunc func() unsafe.Pointer
	DurationFunc   func() int64
	BitRateFunc    func() int64
	FreeFunc       func()
	PtrFunc        func() unsafe.Pointer
}

func (mock *MockFormatContext) NbStreams() uint32 {
	if mock.NbStreamsFunc != nil {
		return mock.NbStreamsFunc()
	}
	var zero uint32
	return zero
}
func (mock *MockFormatContext) StreamsPtr() unsafe.Pointer {
	if mock.StreamsPtrFunc != nil {
		return mock.StreamsPtrFunc()
	}
	var zero unsafe.Pointer
	return zero
}
func (mock *MockFormatContext) Duration() int64 {
	if mock.DurationFunc != nil {
		return mock.DurationFunc()
	}
	var zero int64
	return zero
}
func (mock *MockFormatContext) BitRate() int64 {
	if mock.BitRateFunc != nil {
		return mock.BitRateFunc()
	}
	var zero int64
	return zero
}

func (mock *MockFormatContext) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockFormatContext) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
