// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDictionary creates a new instance of MockDictionary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionary(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionary {
	mock := &MockDictionary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDictionary is an autogenerated mock type for the Dictionary type
type MockDictionary struct {
	mock.Mock
}

type MockDictionary_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionary) EXPECT() *MockDictionary_Expecter {
	return &MockDictionary_Expecter{mock: &_m.Mock}
}

// Free provides a mock function for the type MockDictionary
func (_mock *MockDictionary) Free() {
	_mock.Called()
	return
}

// MockDictionary_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockDictionary_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockDictionary_Expecter) Free() *MockDictionary_Free_Call {
	return &MockDictionary_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockDictionary_Free_Call) Run(run func()) *MockDictionary_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDictionary_Free_Call) Return() *MockDictionary_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDictionary_Free_Call) RunAndReturn(run func()) *MockDictionary_Free_Call {
	_c.Run(run)
	return _c
}

// Ptr provides a mock function for the type MockDictionary
func (_mock *MockDictionary) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockDictionary_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockDictionary_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockDictionary_Expecter) Ptr() *MockDictionary_Ptr_Call {
	return &MockDictionary_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockDictionary_Ptr_Call) Run(run func()) *MockDictionary_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDictionary_Ptr_Call) Return(v unsafe.Pointer) *MockDictionary_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockDictionary_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockDictionary_Ptr_Call {
	_c.Call.Return(run)
	return _c
}
