// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFormatContext creates a new instance of MockFormatContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFormatContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFormatContext {
	mock := &MockFormatContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFormatContext is an autogenerated mock type for the FormatContext type
type MockFormatContext struct {
	mock.Mock
}

type MockFormatContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFormatContext) EXPECT() *MockFormatContext_Expecter {
	return &MockFormatContext_Expecter{mock: &_m.Mock}
}

// BitRate provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) BitRate() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BitRate")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFormatContext_BitRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BitRate'
type MockFormatContext_BitRate_Call struct {
	*mock.Call
}

// BitRate is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) BitRate() *MockFormatContext_BitRate_Call {
	return &MockFormatContext_BitRate_Call{Call: _e.mock.On("BitRate")}
}

func (_c *MockFormatContext_BitRate_Call) Run(run func()) *MockFormatContext_BitRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_BitRate_Call) Return(n int64) *MockFormatContext_BitRate_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFormatContext_BitRate_Call) RunAndReturn(run func() int64) *MockFormatContext_BitRate_Call {
	_c.Call.Return(run)
	return _c
}

// Duration provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) Duration() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFormatContext_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type MockFormatContext_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) Duration() *MockFormatContext_Duration_Call {
	return &MockFormatContext_Duration_Call{Call: _e.mock.On("Duration")}
}

func (_c *MockFormatContext_Duration_Call) Run(run func()) *MockFormatContext_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_Duration_Call) Return(n int64) *MockFormatContext_Duration_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFormatContext_Duration_Call) RunAndReturn(run func() int64) *MockFormatContext_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) Free() {
	_mock.Called()
	return
}

// MockFormatContext_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockFormatContext_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) Free() *MockFormatContext_Free_Call {
	return &MockFormatContext_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockFormatContext_Free_Call) Run(run func()) *MockFormatContext_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_Free_Call) Return() *MockFormatContext_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFormatContext_Free_Call) RunAndReturn(run func()) *MockFormatContext_Free_Call {
	_c.Run(run)
	return _c
}

// NbStreams provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) NbStreams() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NbStreams")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockFormatContext_NbStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NbStreams'
type MockFormatContext_NbStreams_Call struct {
	*mock.Call
}

// NbStreams is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) NbStreams() *MockFormatContext_NbStreams_Call {
	return &MockFormatContext_NbStreams_Call{Call: _e.mock.On("NbStreams")}
}

func (_c *MockFormatContext_NbStreams_Call) Run(run func()) *MockFormatContext_NbStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_NbStreams_Call) Return(v uint32) *MockFormatContext_NbStreams_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFormatContext_NbStreams_Call) RunAndReturn(run func() uint32) *MockFormatContext_NbStreams_Call {
	_c.Call.Return(run)
	return _c
}

// Ptr provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFormatContext_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockFormatContext_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) Ptr() *MockFormatContext_Ptr_Call {
	return &MockFormatContext_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockFormatContext_Ptr_Call) Run(run func()) *MockFormatContext_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_Ptr_Call) Return(v unsafe.Pointer) *MockFormatContext_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFormatContext_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFormatContext_Ptr_Call {
	_c.Call.Return(run)
	return _c
}

// StreamsPtr provides a mock function for the type MockFormatContext
func (_mock *MockFormatContext) StreamsPtr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StreamsPtr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFormatContext_StreamsPtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamsPtr'
type MockFormatContext_StreamsPtr_Call struct {
	*mock.Call
}

// StreamsPtr is a helper method to define mock.On call
func (_e *MockFormatContext_Expecter) StreamsPtr() *MockFormatContext_StreamsPtr_Call {
	return &MockFormatContext_StreamsPtr_Call{Call: _e.mock.On("StreamsPtr")}
}

func (_c *MockFormatContext_StreamsPtr_Call) Run(run func()) *MockFormatContext_StreamsPtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFormatContext_StreamsPtr_Call) Return(v unsafe.Pointer) *MockFormatContext_StreamsPtr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFormatContext_StreamsPtr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFormatContext_StreamsPtr_Call {
	_c.Call.Return(run)
	return _c
}
