// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/ports/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStream creates a new instance of MockStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStream {
	mock := &MockStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStream is an autogenerated mock type for the Stream type
type MockStream struct {
	mock.Mock
}

type MockStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStream) EXPECT() *MockStream_Expecter {
	return &MockStream_Expecter{mock: &_m.Mock}
}

// CodecParameters provides a mock function for the type MockStream
func (_mock *MockStream) CodecParameters() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CodecParameters")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockStream_CodecParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CodecParameters'
type MockStream_CodecParameters_Call struct {
	*mock.Call
}

// CodecParameters is a helper method to define mock.On call
func (_e *MockStream_Expecter) CodecParameters() *MockStream_CodecParameters_Call {
	return &MockStream_CodecParameters_Call{Call: _e.mock.On("CodecParameters")}
}

func (_c *MockStream_CodecParameters_Call) Run(run func()) *MockStream_CodecParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_CodecParameters_Call) Return(v unsafe.Pointer) *MockStream_CodecParameters_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStream_CodecParameters_Call) RunAndReturn(run func() unsafe.Pointer) *MockStream_CodecParameters_Call {
	_c.Call.Return(run)
	return _c
}

// Duration provides a mock function for the type MockStream
func (_mock *MockStream) Duration() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockStream_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type MockStream_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
func (_e *MockStream_Expecter) Duration() *MockStream_Duration_Call {
	return &MockStream_Duration_Call{Call: _e.mock.On("Duration")}
}

func (_c *MockStream_Duration_Call) Run(run func()) *MockStream_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_Duration_Call) Return(n int64) *MockStream_Duration_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStream_Duration_Call) RunAndReturn(run func() int64) *MockStream_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function for the type MockStream
func (_mock *MockStream) Free() {
	_mock.Called()
	return
}

// MockStream_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockStream_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockStream_Expecter) Free() *MockStream_Free_Call {
	return &MockStream_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockStream_Free_Call) Run(run func()) *MockStream_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_Free_Call) Return() *MockStream_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStream_Free_Call) RunAndReturn(run func()) *MockStream_Free_Call {
	_c.Run(run)
	return _c
}

// Index provides a mock function for the type MockStream
func (_mock *MockStream) Index() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockStream_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockStream_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
func (_e *MockStream_Expecter) Index() *MockStream_Index_Call {
	return &MockStream_Index_Call{Call: _e.mock.On("Index")}
}

func (_c *MockStream_Index_Call) Run(run func()) *MockStream_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_Index_Call) Return(n int32) *MockStream_Index_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStream_Index_Call) RunAndReturn(run func() int32) *MockStream_Index_Call {
	_c.Call.Return(run)
	return _c
}

// NbFrames provides a mock function for the type MockStream
func (_mock *MockStream) NbFrames() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NbFrames")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockStream_NbFrames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NbFrames'
type MockStream_NbFrames_Call struct {
	*mock.Call
}

// NbFrames is a helper method to define mock.On call
func (_e *MockStream_Expecter) NbFrames() *MockStream_NbFrames_Call {
	return &MockStream_NbFrames_Call{Call: _e.mock.On("NbFrames")}
}

func (_c *MockStream_NbFrames_Call) Run(run func()) *MockStream_NbFrames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_NbFrames_Call) Return(n int64) *MockStream_NbFrames_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStream_NbFrames_Call) RunAndReturn(run func() int64) *MockStream_NbFrames_Call {
	_c.Call.Return(run)
	return _c
}

// Ptr provides a mock function for the type MockStream
func (_mock *MockStream) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockStream_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockStream_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockStream_Expecter) Ptr() *MockStream_Ptr_Call {
	return &MockStream_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockStream_Ptr_Call) Run(run func()) *MockStream_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_Ptr_Call) Return(v unsafe.Pointer) *MockStream_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStream_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockStream_Ptr_Call {
	_c.Call.Return(run)
	return _c
}

// SetTimeBase provides a mock function for the type MockStream
func (_mock *MockStream) SetTimeBase(v in.AVRational) {
	_mock.Called(v)
	return
}

// MockStream_SetTimeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeBase'
type MockStream_SetTimeBase_Call struct {
	*mock.Call
}

// SetTimeBase is a helper method to define mock.On call
//   - v in.AVRational
func (_e *MockStream_Expecter) SetTimeBase(v interface{}) *MockStream_SetTimeBase_Call {
	return &MockStream_SetTimeBase_Call{Call: _e.mock.On("SetTimeBase", v)}
}

func (_c *MockStream_SetTimeBase_Call) Run(run func(v in.AVRational)) *MockStream_SetTimeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.AVRational
		if args[0] != nil {
			arg0 = args[0].(in.AVRational)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStream_SetTimeBase_Call) Return() *MockStream_SetTimeBase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStream_SetTimeBase_Call) RunAndReturn(run func(v in.AVRational)) *MockStream_SetTimeBase_Call {
	_c.Run(run)
	return _c
}

// TimeBase provides a mock function for the type MockStream
func (_mock *MockStream) TimeBase() in.AVRational {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeBase")
	}

	var r0 in.AVRational
	if returnFunc, ok := ret.Get(0).(func() in.AVRational); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(in.AVRational)
	}
	return r0
}

// MockStream_TimeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeBase'
type MockStream_TimeBase_Call struct {
	*mock.Call
}

// TimeBase is a helper method to define mock.On call
func (_e *MockStream_Expecter) TimeBase() *MockStream_TimeBase_Call {
	return &MockStream_TimeBase_Call{Call: _e.mock.On("TimeBase")}
}

func (_c *MockStream_TimeBase_Call) Run(run func()) *MockStream_TimeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStream_TimeBase_Call) Return(v in.AVRational) *MockStream_TimeBase_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStream_TimeBase_Call) RunAndReturn(run func() in.AVRational) *MockStream_TimeBase_Call {
	_c.Call.Return(run)
	return _c
}
