// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/ports/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCodecContext creates a new instance of MockCodecContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodecContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodecContext {
	mock := &MockCodecContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCodecContext is an autogenerated mock type for the CodecContext type
type MockCodecContext struct {
	mock.Mock
}

type MockCodecContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodecContext) EXPECT() *MockCodecContext_Expecter {
	return &MockCodecContext_Expecter{mock: &_m.Mock}
}

// CodecID provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) CodecID() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CodecID")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_CodecID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CodecID'
type MockCodecContext_CodecID_Call struct {
	*mock.Call
}

// CodecID is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) CodecID() *MockCodecContext_CodecID_Call {
	return &MockCodecContext_CodecID_Call{Call: _e.mock.On("CodecID")}
}

func (_c *MockCodecContext_CodecID_Call) Run(run func()) *MockCodecContext_CodecID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_CodecID_Call) Return(n int32) *MockCodecContext_CodecID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_CodecID_Call) RunAndReturn(run func() int32) *MockCodecContext_CodecID_Call {
	_c.Call.Return(run)
	return _c
}

// CodecType provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) CodecType() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CodecType")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_CodecType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CodecType'
type MockCodecContext_CodecType_Call struct {
	*mock.Call
}

// CodecType is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) CodecType() *MockCodecContext_CodecType_Call {
	return &MockCodecContext_CodecType_Call{Call: _e.mock.On("CodecType")}
}

func (_c *MockCodecContext_CodecType_Call) Run(run func()) *MockCodecContext_CodecType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_CodecType_Call) Return(n int32) *MockCodecContext_CodecType_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_CodecType_Call) RunAndReturn(run func() int32) *MockCodecContext_CodecType_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) Free() {
	_mock.Called()
	return
}

// MockCodecContext_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockCodecContext_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) Free() *MockCodecContext_Free_Call {
	return &MockCodecContext_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockCodecContext_Free_Call) Run(run func()) *MockCodecContext_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_Free_Call) Return() *MockCodecContext_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_Free_Call) RunAndReturn(run func()) *MockCodecContext_Free_Call {
	_c.Run(run)
	return _c
}

// HWDeviceCtx provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) HWDeviceCtx() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HWDeviceCtx")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockCodecContext_HWDeviceCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HWDeviceCtx'
type MockCodecContext_HWDeviceCtx_Call struct {
	*mock.Call
}

// HWDeviceCtx is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) HWDeviceCtx() *MockCodecContext_HWDeviceCtx_Call {
	return &MockCodecContext_HWDeviceCtx_Call{Call: _e.mock.On("HWDeviceCtx")}
}

func (_c *MockCodecContext_HWDeviceCtx_Call) Run(run func()) *MockCodecContext_HWDeviceCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_HWDeviceCtx_Call) Return(v unsafe.Pointer) *MockCodecContext_HWDeviceCtx_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCodecContext_HWDeviceCtx_Call) RunAndReturn(run func() unsafe.Pointer) *MockCodecContext_HWDeviceCtx_Call {
	_c.Call.Return(run)
	return _c
}

// HWFramesCtx provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) HWFramesCtx() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HWFramesCtx")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockCodecContext_HWFramesCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HWFramesCtx'
type MockCodecContext_HWFramesCtx_Call struct {
	*mock.Call
}

// HWFramesCtx is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) HWFramesCtx() *MockCodecContext_HWFramesCtx_Call {
	return &MockCodecContext_HWFramesCtx_Call{Call: _e.mock.On("HWFramesCtx")}
}

func (_c *MockCodecContext_HWFramesCtx_Call) Run(run func()) *MockCodecContext_HWFramesCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_HWFramesCtx_Call) Return(v unsafe.Pointer) *MockCodecContext_HWFramesCtx_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCodecContext_HWFramesCtx_Call) RunAndReturn(run func() unsafe.Pointer) *MockCodecContext_HWFramesCtx_Call {
	_c.Call.Return(run)
	return _c
}

// Height provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) Height() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Height")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_Height_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Height'
type MockCodecContext_Height_Call struct {
	*mock.Call
}

// Height is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) Height() *MockCodecContext_Height_Call {
	return &MockCodecContext_Height_Call{Call: _e.mock.On("Height")}
}

func (_c *MockCodecContext_Height_Call) Run(run func()) *MockCodecContext_Height_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_Height_Call) Return(n int32) *MockCodecContext_Height_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_Height_Call) RunAndReturn(run func() int32) *MockCodecContext_Height_Call {
	_c.Call.Return(run)
	return _c
}

// PixelFormat provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) PixelFormat() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PixelFormat")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_PixelFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PixelFormat'
type MockCodecContext_PixelFormat_Call struct {
	*mock.Call
}

// PixelFormat is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) PixelFormat() *MockCodecContext_PixelFormat_Call {
	return &MockCodecContext_PixelFormat_Call{Call: _e.mock.On("PixelFormat")}
}

func (_c *MockCodecContext_PixelFormat_Call) Run(run func()) *MockCodecContext_PixelFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_PixelFormat_Call) Return(n int32) *MockCodecContext_PixelFormat_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_PixelFormat_Call) RunAndReturn(run func() int32) *MockCodecContext_PixelFormat_Call {
	_c.Call.Return(run)
	return _c
}

// Ptr provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockCodecContext_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockCodecContext_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) Ptr() *MockCodecContext_Ptr_Call {
	return &MockCodecContext_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockCodecContext_Ptr_Call) Run(run func()) *MockCodecContext_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_Ptr_Call) Return(v unsafe.Pointer) *MockCodecContext_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCodecContext_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockCodecContext_Ptr_Call {
	_c.Call.Return(run)
	return _c
}

// SampleFormat provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SampleFormat() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SampleFormat")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_SampleFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleFormat'
type MockCodecContext_SampleFormat_Call struct {
	*mock.Call
}

// SampleFormat is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) SampleFormat() *MockCodecContext_SampleFormat_Call {
	return &MockCodecContext_SampleFormat_Call{Call: _e.mock.On("SampleFormat")}
}

func (_c *MockCodecContext_SampleFormat_Call) Run(run func()) *MockCodecContext_SampleFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_SampleFormat_Call) Return(n int32) *MockCodecContext_SampleFormat_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_SampleFormat_Call) RunAndReturn(run func() int32) *MockCodecContext_SampleFormat_Call {
	_c.Call.Return(run)
	return _c
}

// SampleRate provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SampleRate() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SampleRate")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_SampleRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleRate'
type MockCodecContext_SampleRate_Call struct {
	*mock.Call
}

// SampleRate is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) SampleRate() *MockCodecContext_SampleRate_Call {
	return &MockCodecContext_SampleRate_Call{Call: _e.mock.On("SampleRate")}
}

func (_c *MockCodecContext_SampleRate_Call) Run(run func()) *MockCodecContext_SampleRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_SampleRate_Call) Return(n int32) *MockCodecContext_SampleRate_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_SampleRate_Call) RunAndReturn(run func() int32) *MockCodecContext_SampleRate_Call {
	_c.Call.Return(run)
	return _c
}

// SetHWDeviceCtx provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetHWDeviceCtx(v unsafe.Pointer) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetHWDeviceCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHWDeviceCtx'
type MockCodecContext_SetHWDeviceCtx_Call struct {
	*mock.Call
}

// SetHWDeviceCtx is a helper method to define mock.On call
//   - v unsafe.Pointer
func (_e *MockCodecContext_Expecter) SetHWDeviceCtx(v interface{}) *MockCodecContext_SetHWDeviceCtx_Call {
	return &MockCodecContext_SetHWDeviceCtx_Call{Call: _e.mock.On("SetHWDeviceCtx", v)}
}

func (_c *MockCodecContext_SetHWDeviceCtx_Call) Run(run func(v unsafe.Pointer)) *MockCodecContext_SetHWDeviceCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetHWDeviceCtx_Call) Return() *MockCodecContext_SetHWDeviceCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetHWDeviceCtx_Call) RunAndReturn(run func(v unsafe.Pointer)) *MockCodecContext_SetHWDeviceCtx_Call {
	_c.Run(run)
	return _c
}

// SetHWFramesCtx provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetHWFramesCtx(v unsafe.Pointer) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetHWFramesCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHWFramesCtx'
type MockCodecContext_SetHWFramesCtx_Call struct {
	*mock.Call
}

// SetHWFramesCtx is a helper method to define mock.On call
//   - v unsafe.Pointer
func (_e *MockCodecContext_Expecter) SetHWFramesCtx(v interface{}) *MockCodecContext_SetHWFramesCtx_Call {
	return &MockCodecContext_SetHWFramesCtx_Call{Call: _e.mock.On("SetHWFramesCtx", v)}
}

func (_c *MockCodecContext_SetHWFramesCtx_Call) Run(run func(v unsafe.Pointer)) *MockCodecContext_SetHWFramesCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetHWFramesCtx_Call) Return() *MockCodecContext_SetHWFramesCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetHWFramesCtx_Call) RunAndReturn(run func(v unsafe.Pointer)) *MockCodecContext_SetHWFramesCtx_Call {
	_c.Run(run)
	return _c
}

// SetHeight provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetHeight(v int32) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeight'
type MockCodecContext_SetHeight_Call struct {
	*mock.Call
}

// SetHeight is a helper method to define mock.On call
//   - v int32
func (_e *MockCodecContext_Expecter) SetHeight(v interface{}) *MockCodecContext_SetHeight_Call {
	return &MockCodecContext_SetHeight_Call{Call: _e.mock.On("SetHeight", v)}
}

func (_c *MockCodecContext_SetHeight_Call) Run(run func(v int32)) *MockCodecContext_SetHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetHeight_Call) Return() *MockCodecContext_SetHeight_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetHeight_Call) RunAndReturn(run func(v int32)) *MockCodecContext_SetHeight_Call {
	_c.Run(run)
	return _c
}

// SetPixelFormat provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetPixelFormat(v int32) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetPixelFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPixelFormat'
type MockCodecContext_SetPixelFormat_Call struct {
	*mock.Call
}

// SetPixelFormat is a helper method to define mock.On call
//   - v int32
func (_e *MockCodecContext_Expecter) SetPixelFormat(v interface{}) *MockCodecContext_SetPixelFormat_Call {
	return &MockCodecContext_SetPixelFormat_Call{Call: _e.mock.On("SetPixelFormat", v)}
}

func (_c *MockCodecContext_SetPixelFormat_Call) Run(run func(v int32)) *MockCodecContext_SetPixelFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetPixelFormat_Call) Return() *MockCodecContext_SetPixelFormat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetPixelFormat_Call) RunAndReturn(run func(v int32)) *MockCodecContext_SetPixelFormat_Call {
	_c.Run(run)
	return _c
}

// SetSampleFormat provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetSampleFormat(v int32) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetSampleFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSampleFormat'
type MockCodecContext_SetSampleFormat_Call struct {
	*mock.Call
}

// SetSampleFormat is a helper method to define mock.On call
//   - v int32
func (_e *MockCodecContext_Expecter) SetSampleFormat(v interface{}) *MockCodecContext_SetSampleFormat_Call {
	return &MockCodecContext_SetSampleFormat_Call{Call: _e.mock.On("SetSampleFormat", v)}
}

func (_c *MockCodecContext_SetSampleFormat_Call) Run(run func(v int32)) *MockCodecContext_SetSampleFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetSampleFormat_Call) Return() *MockCodecContext_SetSampleFormat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetSampleFormat_Call) RunAndReturn(run func(v int32)) *MockCodecContext_SetSampleFormat_Call {
	_c.Run(run)
	return _c
}

// SetSampleRate provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetSampleRate(v int32) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetSampleRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSampleRate'
type MockCodecContext_SetSampleRate_Call struct {
	*mock.Call
}

// SetSampleRate is a helper method to define mock.On call
//   - v int32
func (_e *MockCodecContext_Expecter) SetSampleRate(v interface{}) *MockCodecContext_SetSampleRate_Call {
	return &MockCodecContext_SetSampleRate_Call{Call: _e.mock.On("SetSampleRate", v)}
}

func (_c *MockCodecContext_SetSampleRate_Call) Run(run func(v int32)) *MockCodecContext_SetSampleRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetSampleRate_Call) Return() *MockCodecContext_SetSampleRate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetSampleRate_Call) RunAndReturn(run func(v int32)) *MockCodecContext_SetSampleRate_Call {
	_c.Run(run)
	return _c
}

// SetTimeBase provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetTimeBase(v in.AVRational) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetTimeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeBase'
type MockCodecContext_SetTimeBase_Call struct {
	*mock.Call
}

// SetTimeBase is a helper method to define mock.On call
//   - v in.AVRational
func (_e *MockCodecContext_Expecter) SetTimeBase(v interface{}) *MockCodecContext_SetTimeBase_Call {
	return &MockCodecContext_SetTimeBase_Call{Call: _e.mock.On("SetTimeBase", v)}
}

func (_c *MockCodecContext_SetTimeBase_Call) Run(run func(v in.AVRational)) *MockCodecContext_SetTimeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 in.AVRational
		if args[0] != nil {
			arg0 = args[0].(in.AVRational)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetTimeBase_Call) Return() *MockCodecContext_SetTimeBase_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetTimeBase_Call) RunAndReturn(run func(v in.AVRational)) *MockCodecContext_SetTimeBase_Call {
	_c.Run(run)
	return _c
}

// SetWidth provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) SetWidth(v int32) {
	_mock.Called(v)
	return
}

// MockCodecContext_SetWidth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWidth'
type MockCodecContext_SetWidth_Call struct {
	*mock.Call
}

// SetWidth is a helper method to define mock.On call
//   - v int32
func (_e *MockCodecContext_Expecter) SetWidth(v interface{}) *MockCodecContext_SetWidth_Call {
	return &MockCodecContext_SetWidth_Call{Call: _e.mock.On("SetWidth", v)}
}

func (_c *MockCodecContext_SetWidth_Call) Run(run func(v int32)) *MockCodecContext_SetWidth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCodecContext_SetWidth_Call) Return() *MockCodecContext_SetWidth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCodecContext_SetWidth_Call) RunAndReturn(run func(v int32)) *MockCodecContext_SetWidth_Call {
	_c.Run(run)
	return _c
}

// TimeBase provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) TimeBase() in.AVRational {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeBase")
	}

	var r0 in.AVRational
	if returnFunc, ok := ret.Get(0).(func() in.AVRational); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(in.AVRational)
	}
	return r0
}

// MockCodecContext_TimeBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TimeBase'
type MockCodecContext_TimeBase_Call struct {
	*mock.Call
}

// TimeBase is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) TimeBase() *MockCodecContext_TimeBase_Call {
	return &MockCodecContext_TimeBase_Call{Call: _e.mock.On("TimeBase")}
}

func (_c *MockCodecContext_TimeBase_Call) Run(run func()) *MockCodecContext_TimeBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_TimeBase_Call) Return(v in.AVRational) *MockCodecContext_TimeBase_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockCodecContext_TimeBase_Call) RunAndReturn(run func() in.AVRational) *MockCodecContext_TimeBase_Call {
	_c.Call.Return(run)
	return _c
}

// Width provides a mock function for the type MockCodecContext
func (_mock *MockCodecContext) Width() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Width")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockCodecContext_Width_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Width'
type MockCodecContext_Width_Call struct {
	*mock.Call
}

// Width is a helper method to define mock.On call
func (_e *MockCodecContext_Expecter) Width() *MockCodecContext_Width_Call {
	return &MockCodecContext_Width_Call{Call: _e.mock.On("Width")}
}

func (_c *MockCodecContext_Width_Call) Run(run func()) *MockCodecContext_Width_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCodecContext_Width_Call) Return(n int32) *MockCodecContext_Width_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockCodecContext_Width_Call) RunAndReturn(run func() int32) *MockCodecContext_Width_Call {
	_c.Call.Return(run)
	return _c
}
