// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSwresampleContext creates a new instance of MockSwresampleContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwresampleContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwresampleContext {
	mock := &MockSwresampleContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwresampleContext is an autogenerated mock type for the SwresampleContext type
type MockSwresampleContext struct {
	mock.Mock
}

type MockSwresampleContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwresampleContext) EXPECT() *MockSwresampleContext_Expecter {
	return &MockSwresampleContext_Expecter{mock: &_m.Mock}
}

// Free provides a mock function for the type MockSwresampleContext
func (_mock *MockSwresampleContext) Free() {
	_mock.Called()
	return
}

// MockSwresampleContext_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockSwresampleContext_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockSwresampleContext_Expecter) Free() *MockSwresampleContext_Free_Call {
	return &MockSwresampleContext_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockSwresampleContext_Free_Call) Run(run func()) *MockSwresampleContext_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSwresampleContext_Free_Call) Return() *MockSwresampleContext_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSwresampleContext_Free_Call) RunAndReturn(run func()) *MockSwresampleContext_Free_Call {
	_c.Run(run)
	return _c
}

// Ptr provides a mock function for the type MockSwresampleContext
func (_mock *MockSwresampleContext) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockSwresampleContext_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockSwresampleContext_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockSwresampleContext_Expecter) Ptr() *MockSwresampleContext_Ptr_Call {
	return &MockSwresampleContext_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockSwresampleContext_Ptr_Call) Run(run func()) *MockSwresampleContext_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSwresampleContext_Ptr_Call) Return(v unsafe.Pointer) *MockSwresampleContext_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockSwresampleContext_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockSwresampleContext_Ptr_Call {
	_c.Call.Return(run)
	return _c
}
