// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSwscaleContext creates a new instance of MockSwscaleContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwscaleContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwscaleContext {
	mock := &MockSwscaleContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwscaleContext is an autogenerated mock type for the SwscaleContext type
type MockSwscaleContext struct {
	mock.Mock
}

type MockSwscaleContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwscaleContext) EXPECT() *MockSwscaleContext_Expecter {
	return &MockSwscaleContext_Expecter{mock: &_m.Mock}
}

// Free provides a mock function for the type MockSwscaleContext
func (_mock *MockSwscaleContext) Free() {
	_mock.Called()
	return
}

// MockSwscaleContext_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockSwscaleContext_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockSwscaleContext_Expecter) Free() *MockSwscaleContext_Free_Call {
	return &MockSwscaleContext_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockSwscaleContext_Free_Call) Run(run func()) *MockSwscaleContext_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSwscaleContext_Free_Call) Return() *MockSwscaleContext_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSwscaleContext_Free_Call) RunAndReturn(run func()) *MockSwscaleContext_Free_Call {
	_c.Run(run)
	return _c
}

// Ptr provides a mock function for the type MockSwscaleContext
func (_mock *MockSwscaleContext) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockSwscaleContext_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockSwscaleContext_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockSwscaleContext_Expecter) Ptr() *MockSwscaleContext_Ptr_Call {
	return &MockSwscaleContext_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockSwscaleContext_Ptr_Call) Run(run func()) *MockSwscaleContext_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSwscaleContext_Ptr_Call) Return(v unsafe.Pointer) *MockSwscaleContext_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockSwscaleContext_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockSwscaleContext_Ptr_Call {
	_c.Call.Return(run)
	return _c
}
