// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFilterGraph creates a new instance of MockFilterGraph. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterGraph(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterGraph {
	mock := &MockFilterGraph{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilterGraph is an autogenerated mock type for the FilterGraph type
type MockFilterGraph struct {
	mock.Mock
}

type MockFilterGraph_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterGraph) EXPECT() *MockFilterGraph_Expecter {
	return &MockFilterGraph_Expecter{mock: &_m.Mock}
}

// Free provides a mock function for the type MockFilterGraph
func (_mock *MockFilterGraph) Free() {
	_mock.Called()
	return
}

// MockFilterGraph_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockFilterGraph_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockFilterGraph_Expecter) Free() *MockFilterGraph_Free_Call {
	return &MockFilterGraph_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockFilterGraph_Free_Call) Run(run func()) *MockFilterGraph_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilterGraph_Free_Call) Return() *MockFilterGraph_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFilterGraph_Free_Call) RunAndReturn(run func()) *MockFilterGraph_Free_Call {
	_c.Run(run)
	return _c
}

// Ptr provides a mock function for the type MockFilterGraph
func (_mock *MockFilterGraph) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFilterGraph_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockFilterGraph_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockFilterGraph_Expecter) Ptr() *MockFilterGraph_Ptr_Call {
	return &MockFilterGraph_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockFilterGraph_Ptr_Call) Run(run func()) *MockFilterGraph_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilterGraph_Ptr_Call) Return(v unsafe.Pointer) *MockFilterGraph_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFilterGraph_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFilterGraph_Ptr_Call {
	_c.Call.Return(run)
	return _c
}
