// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFrame creates a new instance of MockFrame. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFrame(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFrame {
	mock := &MockFrame{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFrame is an autogenerated mock type for the Frame type
type MockFrame struct {
	mock.Mock
}

type MockFrame_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFrame) EXPECT() *MockFrame_Expecter {
	return &MockFrame_Expecter{mock: &_m.Mock}
}

// DataPtr provides a mock function for the type MockFrame
func (_mock *MockFrame) DataPtr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataPtr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFrame_DataPtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataPtr'
type MockFrame_DataPtr_Call struct {
	*mock.Call
}

// DataPtr is a helper method to define mock.On call
func (_e *MockFrame_Expecter) DataPtr() *MockFrame_DataPtr_Call {
	return &MockFrame_DataPtr_Call{Call: _e.mock.On("DataPtr")}
}

func (_c *MockFrame_DataPtr_Call) Run(run func()) *MockFrame_DataPtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_DataPtr_Call) Return(v unsafe.Pointer) *MockFrame_DataPtr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFrame_DataPtr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFrame_DataPtr_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function for the type MockFrame
func (_mock *MockFrame) Format() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Format")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockFrame_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type MockFrame_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Format() *MockFrame_Format_Call {
	return &MockFrame_Format_Call{Call: _e.mock.On("Format")}
}

func (_c *MockFrame_Format_Call) Run(run func()) *MockFrame_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Format_Call) Return(n int32) *MockFrame_Format_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_Format_Call) RunAndReturn(run func() int32) *MockFrame_Format_Call {
	_c.Call.Return(run)
	return _c
}

// Free provides a mock function for the type MockFrame
func (_mock *MockFrame) Free() {
	_mock.Called()
	return
}

// MockFrame_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockFrame_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Free() *MockFrame_Free_Call {
	return &MockFrame_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockFrame_Free_Call) Run(run func()) *MockFrame_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Free_Call) Return() *MockFrame_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_Free_Call) RunAndReturn(run func()) *MockFrame_Free_Call {
	_c.Run(run)
	return _c
}

// HWFramesCtx provides a mock function for the type MockFrame
func (_mock *MockFrame) HWFramesCtx() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HWFramesCtx")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFrame_HWFramesCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HWFramesCtx'
type MockFrame_HWFramesCtx_Call struct {
	*mock.Call
}

// HWFramesCtx is a helper method to define mock.On call
func (_e *MockFrame_Expecter) HWFramesCtx() *MockFrame_HWFramesCtx_Call {
	return &MockFrame_HWFramesCtx_Call{Call: _e.mock.On("HWFramesCtx")}
}

func (_c *MockFrame_HWFramesCtx_Call) Run(run func()) *MockFrame_HWFramesCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_HWFramesCtx_Call) Return(v unsafe.Pointer) *MockFrame_HWFramesCtx_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFrame_HWFramesCtx_Call) RunAndReturn(run func() unsafe.Pointer) *MockFrame_HWFramesCtx_Call {
	_c.Call.Return(run)
	return _c
}

// Height provides a mock function for the type MockFrame
func (_mock *MockFrame) Height() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Height")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockFrame_Height_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Height'
type MockFrame_Height_Call struct {
	*mock.Call
}

// Height is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Height() *MockFrame_Height_Call {
	return &MockFrame_Height_Call{Call: _e.mock.On("Height")}
}

func (_c *MockFrame_Height_Call) Run(run func()) *MockFrame_Height_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Height_Call) Return(n int32) *MockFrame_Height_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_Height_Call) RunAndReturn(run func() int32) *MockFrame_Height_Call {
	_c.Call.Return(run)
	return _c
}

// LinesizePtr provides a mock function for the type MockFrame
func (_mock *MockFrame) LinesizePtr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LinesizePtr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFrame_LinesizePtr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinesizePtr'
type MockFrame_LinesizePtr_Call struct {
	*mock.Call
}

// LinesizePtr is a helper method to define mock.On call
func (_e *MockFrame_Expecter) LinesizePtr() *MockFrame_LinesizePtr_Call {
	return &MockFrame_LinesizePtr_Call{Call: _e.mock.On("LinesizePtr")}
}

func (_c *MockFrame_LinesizePtr_Call) Run(run func()) *MockFrame_LinesizePtr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_LinesizePtr_Call) Return(v unsafe.Pointer) *MockFrame_LinesizePtr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFrame_LinesizePtr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFrame_LinesizePtr_Call {
	_c.Call.Return(run)
	return _c
}

// NbSamples provides a mock function for the type MockFrame
func (_mock *MockFrame) NbSamples() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NbSamples")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockFrame_NbSamples_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NbSamples'
type MockFrame_NbSamples_Call struct {
	*mock.Call
}

// NbSamples is a helper method to define mock.On call
func (_e *MockFrame_Expecter) NbSamples() *MockFrame_NbSamples_Call {
	return &MockFrame_NbSamples_Call{Call: _e.mock.On("NbSamples")}
}

func (_c *MockFrame_NbSamples_Call) Run(run func()) *MockFrame_NbSamples_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_NbSamples_Call) Return(n int32) *MockFrame_NbSamples_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_NbSamples_Call) RunAndReturn(run func() int32) *MockFrame_NbSamples_Call {
	_c.Call.Return(run)
	return _c
}

// PktDts provides a mock function for the type MockFrame
func (_mock *MockFrame) PktDts() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PktDts")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFrame_PktDts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PktDts'
type MockFrame_PktDts_Call struct {
	*mock.Call
}

// PktDts is a helper method to define mock.On call
func (_e *MockFrame_Expecter) PktDts() *MockFrame_PktDts_Call {
	return &MockFrame_PktDts_Call{Call: _e.mock.On("PktDts")}
}

func (_c *MockFrame_PktDts_Call) Run(run func()) *MockFrame_PktDts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_PktDts_Call) Return(n int64) *MockFrame_PktDts_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_PktDts_Call) RunAndReturn(run func() int64) *MockFrame_PktDts_Call {
	_c.Call.Return(run)
	return _c
}

// Ptr provides a mock function for the type MockFrame
func (_mock *MockFrame) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockFrame_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockFrame_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Ptr() *MockFrame_Ptr_Call {
	return &MockFrame_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockFrame_Ptr_Call) Run(run func()) *MockFrame_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Ptr_Call) Return(v unsafe.Pointer) *MockFrame_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFrame_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockFrame_Ptr_Call {
	_c.Call.Return(run)
	return _c
}

// Pts provides a mock function for the type MockFrame
func (_mock *MockFrame) Pts() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pts")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFrame_Pts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pts'
type MockFrame_Pts_Call struct {
	*mock.Call
}

// Pts is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Pts() *MockFrame_Pts_Call {
	return &MockFrame_Pts_Call{Call: _e.mock.On("Pts")}
}

func (_c *MockFrame_Pts_Call) Run(run func()) *MockFrame_Pts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Pts_Call) Return(n int64) *MockFrame_Pts_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_Pts_Call) RunAndReturn(run func() int64) *MockFrame_Pts_Call {
	_c.Call.Return(run)
	return _c
}

// SampleRate provides a mock function for the type MockFrame
func (_mock *MockFrame) SampleRate() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SampleRate")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockFrame_SampleRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SampleRate'
type MockFrame_SampleRate_Call struct {
	*mock.Call
}

// SampleRate is a helper method to define mock.On call
func (_e *MockFrame_Expecter) SampleRate() *MockFrame_SampleRate_Call {
	return &MockFrame_SampleRate_Call{Call: _e.mock.On("SampleRate")}
}

func (_c *MockFrame_SampleRate_Call) Run(run func()) *MockFrame_SampleRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_SampleRate_Call) Return(n int32) *MockFrame_SampleRate_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_SampleRate_Call) RunAndReturn(run func() int32) *MockFrame_SampleRate_Call {
	_c.Call.Return(run)
	return _c
}

// SetFormat provides a mock function for the type MockFrame
func (_mock *MockFrame) SetFormat(v int32) {
	_mock.Called(v)
	return
}

// MockFrame_SetFormat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFormat'
type MockFrame_SetFormat_Call struct {
	*mock.Call
}

// SetFormat is a helper method to define mock.On call
//   - v int32
func (_e *MockFrame_Expecter) SetFormat(v interface{}) *MockFrame_SetFormat_Call {
	return &MockFrame_SetFormat_Call{Call: _e.mock.On("SetFormat", v)}
}

func (_c *MockFrame_SetFormat_Call) Run(run func(v int32)) *MockFrame_SetFormat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetFormat_Call) Return() *MockFrame_SetFormat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetFormat_Call) RunAndReturn(run func(v int32)) *MockFrame_SetFormat_Call {
	_c.Run(run)
	return _c
}

// SetHWFramesCtx provides a mock function for the type MockFrame
func (_mock *MockFrame) SetHWFramesCtx(v unsafe.Pointer) {
	_mock.Called(v)
	return
}

// MockFrame_SetHWFramesCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHWFramesCtx'
type MockFrame_SetHWFramesCtx_Call struct {
	*mock.Call
}

// SetHWFramesCtx is a helper method to define mock.On call
//   - v unsafe.Pointer
func (_e *MockFrame_Expecter) SetHWFramesCtx(v interface{}) *MockFrame_SetHWFramesCtx_Call {
	return &MockFrame_SetHWFramesCtx_Call{Call: _e.mock.On("SetHWFramesCtx", v)}
}

func (_c *MockFrame_SetHWFramesCtx_Call) Run(run func(v unsafe.Pointer)) *MockFrame_SetHWFramesCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetHWFramesCtx_Call) Return() *MockFrame_SetHWFramesCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetHWFramesCtx_Call) RunAndReturn(run func(v unsafe.Pointer)) *MockFrame_SetHWFramesCtx_Call {
	_c.Run(run)
	return _c
}

// SetHeight provides a mock function for the type MockFrame
func (_mock *MockFrame) SetHeight(v int32) {
	_mock.Called(v)
	return
}

// MockFrame_SetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeight'
type MockFrame_SetHeight_Call struct {
	*mock.Call
}

// SetHeight is a helper method to define mock.On call
//   - v int32
func (_e *MockFrame_Expecter) SetHeight(v interface{}) *MockFrame_SetHeight_Call {
	return &MockFrame_SetHeight_Call{Call: _e.mock.On("SetHeight", v)}
}

func (_c *MockFrame_SetHeight_Call) Run(run func(v int32)) *MockFrame_SetHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetHeight_Call) Return() *MockFrame_SetHeight_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetHeight_Call) RunAndReturn(run func(v int32)) *MockFrame_SetHeight_Call {
	_c.Run(run)
	return _c
}

// SetNbSamples provides a mock function for the type MockFrame
func (_mock *MockFrame) SetNbSamples(v int32) {
	_mock.Called(v)
	return
}

// MockFrame_SetNbSamples_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNbSamples'
type MockFrame_SetNbSamples_Call struct {
	*mock.Call
}

// SetNbSamples is a helper method to define mock.On call
//   - v int32
func (_e *MockFrame_Expecter) SetNbSamples(v interface{}) *MockFrame_SetNbSamples_Call {
	return &MockFrame_SetNbSamples_Call{Call: _e.mock.On("SetNbSamples", v)}
}

func (_c *MockFrame_SetNbSamples_Call) Run(run func(v int32)) *MockFrame_SetNbSamples_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetNbSamples_Call) Return() *MockFrame_SetNbSamples_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetNbSamples_Call) RunAndReturn(run func(v int32)) *MockFrame_SetNbSamples_Call {
	_c.Run(run)
	return _c
}

// SetPktDts provides a mock function for the type MockFrame
func (_mock *MockFrame) SetPktDts(v int64) {
	_mock.Called(v)
	return
}

// MockFrame_SetPktDts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPktDts'
type MockFrame_SetPktDts_Call struct {
	*mock.Call
}

// SetPktDts is a helper method to define mock.On call
//   - v int64
func (_e *MockFrame_Expecter) SetPktDts(v interface{}) *MockFrame_SetPktDts_Call {
	return &MockFrame_SetPktDts_Call{Call: _e.mock.On("SetPktDts", v)}
}

func (_c *MockFrame_SetPktDts_Call) Run(run func(v int64)) *MockFrame_SetPktDts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetPktDts_Call) Return() *MockFrame_SetPktDts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetPktDts_Call) RunAndReturn(run func(v int64)) *MockFrame_SetPktDts_Call {
	_c.Run(run)
	return _c
}

// SetPts provides a mock function for the type MockFrame
func (_mock *MockFrame) SetPts(v int64) {
	_mock.Called(v)
	return
}

// MockFrame_SetPts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPts'
type MockFrame_SetPts_Call struct {
	*mock.Call
}

// SetPts is a helper method to define mock.On call
//   - v int64
func (_e *MockFrame_Expecter) SetPts(v interface{}) *MockFrame_SetPts_Call {
	return &MockFrame_SetPts_Call{Call: _e.mock.On("SetPts", v)}
}

func (_c *MockFrame_SetPts_Call) Run(run func(v int64)) *MockFrame_SetPts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetPts_Call) Return() *MockFrame_SetPts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetPts_Call) RunAndReturn(run func(v int64)) *MockFrame_SetPts_Call {
	_c.Run(run)
	return _c
}

// SetSampleRate provides a mock function for the type MockFrame
func (_mock *MockFrame) SetSampleRate(v int32) {
	_mock.Called(v)
	return
}

// MockFrame_SetSampleRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSampleRate'
type MockFrame_SetSampleRate_Call struct {
	*mock.Call
}

// SetSampleRate is a helper method to define mock.On call
//   - v int32
func (_e *MockFrame_Expecter) SetSampleRate(v interface{}) *MockFrame_SetSampleRate_Call {
	return &MockFrame_SetSampleRate_Call{Call: _e.mock.On("SetSampleRate", v)}
}

func (_c *MockFrame_SetSampleRate_Call) Run(run func(v int32)) *MockFrame_SetSampleRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetSampleRate_Call) Return() *MockFrame_SetSampleRate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetSampleRate_Call) RunAndReturn(run func(v int32)) *MockFrame_SetSampleRate_Call {
	_c.Run(run)
	return _c
}

// SetWidth provides a mock function for the type MockFrame
func (_mock *MockFrame) SetWidth(v int32) {
	_mock.Called(v)
	return
}

// MockFrame_SetWidth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWidth'
type MockFrame_SetWidth_Call struct {
	*mock.Call
}

// SetWidth is a helper method to define mock.On call
//   - v int32
func (_e *MockFrame_Expecter) SetWidth(v interface{}) *MockFrame_SetWidth_Call {
	return &MockFrame_SetWidth_Call{Call: _e.mock.On("SetWidth", v)}
}

func (_c *MockFrame_SetWidth_Call) Run(run func(v int32)) *MockFrame_SetWidth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFrame_SetWidth_Call) Return() *MockFrame_SetWidth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFrame_SetWidth_Call) RunAndReturn(run func(v int32)) *MockFrame_SetWidth_Call {
	_c.Run(run)
	return _c
}

// Width provides a mock function for the type MockFrame
func (_mock *MockFrame) Width() int32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Width")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func() int32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockFrame_Width_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Width'
type MockFrame_Width_Call struct {
	*mock.Call
}

// Width is a helper method to define mock.On call
func (_e *MockFrame_Expecter) Width() *MockFrame_Width_Call {
	return &MockFrame_Width_Call{Call: _e.mock.On("Width")}
}

func (_c *MockFrame_Width_Call) Run(run func()) *MockFrame_Width_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFrame_Width_Call) Return(n int32) *MockFrame_Width_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFrame_Width_Call) RunAndReturn(run func() int32) *MockFrame_Width_Call {
	_c.Call.Return(run)
	return _c
}
