// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPacket creates a new instance of MockPacket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPacket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPacket {
	mock := &MockPacket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPacket is an autogenerated mock type for the Packet type
type MockPacket struct {
	mock.Mock
}

type MockPacket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPacket) EXPECT() *MockPacket_Expecter {
	return &MockPacket_Expecter{mock: &_m.Mock}
}

// Free provides a mock function for the type MockPacket
func (_mock *MockPacket) Free() {
	_mock.Called()
	return
}

// MockPacket_Free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Free'
type MockPacket_Free_Call struct {
	*mock.Call
}

// Free is a helper method to define mock.On call
func (_e *MockPacket_Expecter) Free() *MockPacket_Free_Call {
	return &MockPacket_Free_Call{Call: _e.mock.On("Free")}
}

func (_c *MockPacket_Free_Call) Run(run func()) *MockPacket_Free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPacket_Free_Call) Return() *MockPacket_Free_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPacket_Free_Call) RunAndReturn(run func()) *MockPacket_Free_Call {
	_c.Run(run)
	return _c
}

// Ptr provides a mock function for the type MockPacket
func (_mock *MockPacket) Ptr() unsafe.Pointer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ptr")
	}

	var r0 unsafe.Pointer
	if returnFunc, ok := ret.Get(0).(func() unsafe.Pointer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	return r0
}

// MockPacket_Ptr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ptr'
type MockPacket_Ptr_Call struct {
	*mock.Call
}

// Ptr is a helper method to define mock.On call
func (_e *MockPacket_Expecter) Ptr() *MockPacket_Ptr_Call {
	return &MockPacket_Ptr_Call{Call: _e.mock.On("Ptr")}
}

func (_c *MockPacket_Ptr_Call) Run(run func()) *MockPacket_Ptr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPacket_Ptr_Call) Return(v unsafe.Pointer) *MockPacket_Ptr_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockPacket_Ptr_Call) RunAndReturn(run func() unsafe.Pointer) *MockPacket_Ptr_Call {
	_c.Call.Return(run)
	return _c
}
