// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockStream is a test mock for Stream.
type MockStream struct {
	IndexFunc              func() int32
	SetIndexFunc           func(v int32)
	CodecParametersFunc    func() unsafe.Pointer
	SetCodecParametersFunc func(v unsafe.Pointer)
	TimeBaseFunc           func() AVRational
	SetTimeBaseFunc        func(v AVRational)
	DurationFunc           func() int64
	SetDurationFunc        func(v int64)
	NbFramesFunc           func() int64
	SetNbFramesFunc        func(v int64)
	FreeFunc               func()
	PtrFunc                func() unsafe.Pointer
}

func (mock *MockStream) Index() int32 {
	if mock.IndexFunc != nil {
		return mock.IndexFunc()
	}
	var zero int32
	return zero
}

func (mock *MockStream) SetIndex(v int32) {
	if mock.SetIndexFunc != nil {
		mock.SetIndexFunc(v)
	}
}
func (mock *MockStream) CodecParameters() unsafe.Pointer {
	if mock.CodecParametersFunc != nil {
		return mock.CodecParametersFunc()
	}
	var zero unsafe.Pointer
	return zero
}

func (mock *MockStream) SetCodecParameters(v unsafe.Pointer) {
	if mock.SetCodecParametersFunc != nil {
		mock.SetCodecParametersFunc(v)
	}
}
func (mock *MockStream) TimeBase() AVRational {
	if mock.TimeBaseFunc != nil {
		return mock.TimeBaseFunc()
	}
	var zero AVRational
	return zero
}

func (mock *MockStream) SetTimeBase(v AVRational) {
	if mock.SetTimeBaseFunc != nil {
		mock.SetTimeBaseFunc(v)
	}
}
func (mock *MockStream) Duration() int64 {
	if mock.DurationFunc != nil {
		return mock.DurationFunc()
	}
	var zero int64
	return zero
}

func (mock *MockStream) SetDuration(v int64) {
	if mock.SetDurationFunc != nil {
		mock.SetDurationFunc(v)
	}
}
func (mock *MockStream) NbFrames() int64 {
	if mock.NbFramesFunc != nil {
		return mock.NbFramesFunc()
	}
	var zero int64
	return zero
}

func (mock *MockStream) SetNbFrames(v int64) {
	if mock.SetNbFramesFunc != nil {
		mock.SetNbFramesFunc(v)
	}
}

func (mock *MockStream) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockStream) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
