// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockSwresampleContext is a test mock for SwresampleContext.
type MockSwresampleContext struct {
	FreeFunc func()
	PtrFunc  func() unsafe.Pointer
}

func (mock *MockSwresampleContext) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockSwresampleContext) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
