// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockSwscaleContext is a test mock for SwscaleContext.
type MockSwscaleContext struct {
	GetContextFunc  func(int32, int32, int32, int32, int32, int32, int32, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) unsafe.Pointer
	ScaleFunc       func(unsafe.Pointer, unsafe.Pointer, int32, int32, int32, unsafe.Pointer, int32) int32
	FreeContextFunc func(unsafe.Pointer)
	FreeFunc        func()
	PtrFunc         func() unsafe.Pointer
}

func (mock *MockSwscaleContext) GetContext(srcw int32, srch int32, srcformat int32, dstw int32, dsth int32, dstformat int32, flags int32, srcfilter unsafe.Pointer, dstfilter unsafe.Pointer, param unsafe.Pointer) unsafe.Pointer {
	if mock.GetContextFunc != nil {
		return mock.GetContextFunc(srcw, srch, srcformat, dstw, dsth, dstformat, flags, srcfilter, dstfilter, param)
	}
	var zero unsafe.Pointer
	return zero
}

func (mock *MockSwscaleContext) Scale(c unsafe.Pointer, srcslice unsafe.Pointer, srcstride int32, srcslicey int32, srcsliceh int32, dst unsafe.Pointer, dststride int32) int32 {
	if mock.ScaleFunc != nil {
		return mock.ScaleFunc(c, srcslice, srcstride, srcslicey, srcsliceh, dst, dststride)
	}
	var zero int32
	return zero
}

func (mock *MockSwscaleContext) FreeContext(swscontext unsafe.Pointer) {
	if mock.FreeContextFunc != nil {
		mock.FreeContextFunc(swscontext)
		return
	}
}

func (mock *MockSwscaleContext) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockSwscaleContext) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
