// Code generated by ffmpeggen. DO NOT EDIT.

package mocks

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// MockSwscaleContext is a test mock for SwscaleContext.
type MockSwscaleContext struct {
	FreeFunc func()
	PtrFunc  func() unsafe.Pointer
}

func (mock *MockSwscaleContext) Free() {
	if mock.FreeFunc != nil {
		mock.FreeFunc()
	}
}

func (mock *MockSwscaleContext) Ptr() unsafe.Pointer {
	if mock.PtrFunc != nil {
		return mock.PtrFunc()
	}
	return nil
}
