// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// FilterGraph is the public interface for avfilter domain operations.
type FilterGraph interface {
	GraphAlloc() unsafe.Pointer
	GraphFree(graph unsafe.Pointer)
	GraphCreateFilter(filtCtx unsafe.Pointer, filt unsafe.Pointer, name *byte, args *byte, opaque unsafe.Pointer, graphCtx unsafe.Pointer) int32
	GraphParsePtr(graph unsafe.Pointer, filters *byte, inputs unsafe.Pointer, outputs unsafe.Pointer, logCtx unsafe.Pointer) int32
	GraphConfig(graphctx unsafe.Pointer, logCtx unsafe.Pointer) int32
	GetByName(name *byte) unsafe.Pointer
	BuffersrcAddFrameFlags(bufferSrc unsafe.Pointer, frame unsafe.Pointer, flags int32) int32
	BuffersinkGetFrame(ctx unsafe.Pointer, frame unsafe.Pointer) int32
	Free()
	Ptr() unsafe.Pointer
}
