// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// CodecContext is the public interface for codec domain operations.
type CodecContext interface {
	FindDecoder(id int32) unsafe.Pointer
	FindEncoder(id int32) unsafe.Pointer
	FindDecoderByName(name *byte) unsafe.Pointer
	FindEncoderByName(name *byte) unsafe.Pointer
	AllocContext3(codec unsafe.Pointer) unsafe.Pointer
	FreeContext(avctx unsafe.Pointer)
	Open2(avctx unsafe.Pointer, codec unsafe.Pointer, options unsafe.Pointer) int32
	SendPacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32
	ReceiveFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32
	SendFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32
	ReceivePacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32
	ParametersToContext(codec unsafe.Pointer, par unsafe.Pointer) int32
	ParametersFromContext(par unsafe.Pointer, codec unsafe.Pointer) int32
	CodecType() int32
	SetCodecType(v int32)
	CodecID() int32
	SetCodecID(v int32)
	TimeBase() AVRational
	SetTimeBase(v AVRational)
	Width() int32
	SetWidth(v int32)
	Height() int32
	SetHeight(v int32)
	PixelFormat() int32
	SetPixelFormat(v int32)
	SampleRate() int32
	SetSampleRate(v int32)
	SampleFormat() int32
	SetSampleFormat(v int32)
	HWDeviceCtx() unsafe.Pointer
	SetHWDeviceCtx(v unsafe.Pointer)
	HWFramesCtx() unsafe.Pointer
	SetHWFramesCtx(v unsafe.Pointer)
	Free()
	Ptr() unsafe.Pointer
}
