// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// CodecContext is the public interface for codec domain operations.
// It exposes struct field accessors and lifecycle methods.
// Low-level C API methods are available on the concrete wrapper type
// but are not part of this interface contract.
type CodecContext interface {
	CodecType() int32
	CodecID() int32
	TimeBase() AVRational
	SetTimeBase(v AVRational)
	Width() int32
	SetWidth(v int32)
	Height() int32
	SetHeight(v int32)
	PixelFormat() int32
	SetPixelFormat(v int32)
	SampleRate() int32
	SetSampleRate(v int32)
	SampleFormat() int32
	SetSampleFormat(v int32)
	HWDeviceCtx() unsafe.Pointer
	SetHWDeviceCtx(v unsafe.Pointer)
	HWFramesCtx() unsafe.Pointer
	SetHWFramesCtx(v unsafe.Pointer)
	Free()
	Ptr() unsafe.Pointer
}
