// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Dictionary is the public interface for dict domain operations.
// It exposes struct field accessors and lifecycle methods.
// Low-level C API methods are available on the concrete wrapper type
// but are not part of this interface contract.
type Dictionary interface {
	Free()
	Ptr() unsafe.Pointer
}
