// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// FormatContext is the public interface for format domain operations.
type FormatContext interface {
	AllocContext() unsafe.Pointer
	FreeContext(s unsafe.Pointer)
	OpenInput(ps unsafe.Pointer, uRL *byte, fmt unsafe.Pointer, options unsafe.Pointer) int32
	FindStreamInfo(ic unsafe.Pointer, options unsafe.Pointer) int32
	ReadFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32
	CloseInput(s unsafe.Pointer)
	AllocOutputContext2(ctx unsafe.Pointer, oformat unsafe.Pointer, formatName *byte, filename *byte) int32
	NewStream(s unsafe.Pointer, c unsafe.Pointer) unsafe.Pointer
	WriteHeader(s unsafe.Pointer, options unsafe.Pointer) int32
	InterleavedWriteFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32
	WriteTrailer(s unsafe.Pointer) int32
	NbStreams() uint32
	SetNbStreams(v uint32)
	Free()
	Ptr() unsafe.Pointer
}
