// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// FormatContext is the public interface for format domain operations.
// It exposes struct field accessors and lifecycle methods.
// Low-level C API methods are available on the concrete wrapper type
// but are not part of this interface contract.
type FormatContext interface {
	NbStreams() uint32
	StreamsPtr() unsafe.Pointer
	Duration() int64
	BitRate() int64
	Free()
	Ptr() unsafe.Pointer
}
