// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Frame is the public interface for frame domain operations.
// It exposes struct field accessors and lifecycle methods.
// Low-level C API methods are available on the concrete wrapper type
// but are not part of this interface contract.
type Frame interface {
	DataPtr() unsafe.Pointer
	LinesizePtr() unsafe.Pointer
	Width() int32
	SetWidth(v int32)
	Height() int32
	SetHeight(v int32)
	NbSamples() int32
	SetNbSamples(v int32)
	Format() int32
	SetFormat(v int32)
	Pts() int64
	SetPts(v int64)
	PktDts() int64
	SetPktDts(v int64)
	SampleRate() int32
	SetSampleRate(v int32)
	HWFramesCtx() unsafe.Pointer
	SetHWFramesCtx(v unsafe.Pointer)
	Free()
	Ptr() unsafe.Pointer
}
