// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Frame is the public interface for frame domain operations.
type Frame interface {
	Alloc() unsafe.Pointer
	FreePtr(frame unsafe.Pointer)
	Unref(frame unsafe.Pointer)
	Ref(dst unsafe.Pointer, src unsafe.Pointer) int32
	Clone(src unsafe.Pointer) unsafe.Pointer
	GetBuffer(frame unsafe.Pointer, align int32) int32
	IsWritable(frame unsafe.Pointer) int32
	MakeWritable(frame unsafe.Pointer) int32
	DataPtr() unsafe.Pointer
	LinesizePtr() unsafe.Pointer
	Width() int32
	SetWidth(v int32)
	Height() int32
	SetHeight(v int32)
	NbSamples() int32
	SetNbSamples(v int32)
	Format() int32
	SetFormat(v int32)
	Pts() int64
	SetPts(v int64)
	PktDts() int64
	SetPktDts(v int64)
	SampleRate() int32
	SetSampleRate(v int32)
	HWFramesCtx() unsafe.Pointer
	SetHWFramesCtx(v unsafe.Pointer)
	Free()
	Ptr() unsafe.Pointer
}
