// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Frame is the public interface for frame domain operations.
type Frame interface {
	Alloc() unsafe.Pointer
	FreePtr(frame unsafe.Pointer)
	Unref(frame unsafe.Pointer)
	Ref(dst unsafe.Pointer, src unsafe.Pointer) int32
	Clone(src unsafe.Pointer) unsafe.Pointer
	GetBuffer(frame unsafe.Pointer, align int32) int32
	IsWritable(frame unsafe.Pointer) int32
	MakeWritable(frame unsafe.Pointer) int32
	Free()
	Ptr() unsafe.Pointer
}
