// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Packet is the public interface for packet domain operations.
type Packet interface {
	Alloc() unsafe.Pointer
	FreePtr(pkt unsafe.Pointer)
	Unref(pkt unsafe.Pointer)
	Ref(dst unsafe.Pointer, src unsafe.Pointer) int32
	RescaleTs(pkt unsafe.Pointer, tbSrc AVRational, tbDst AVRational)
	Free()
	Ptr() unsafe.Pointer
}
