// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Stream is the public interface for stream domain operations.
// It exposes struct field accessors and lifecycle methods.
// Low-level C API methods are available on the concrete wrapper type
// but are not part of this interface contract.
type Stream interface {
	Index() int32
	CodecParameters() unsafe.Pointer
	TimeBase() AVRational
	SetTimeBase(v AVRational)
	Duration() int64
	NbFrames() int64
	Free()
	Ptr() unsafe.Pointer
}
