// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Stream is the public interface for stream domain operations.
type Stream interface {
	Index() int32
	SetIndex(v int32)
	CodecParameters() unsafe.Pointer
	SetCodecParameters(v unsafe.Pointer)
	TimeBase() AVRational
	SetTimeBase(v AVRational)
	Duration() int64
	SetDuration(v int64)
	NbFrames() int64
	SetNbFrames(v int64)
	Free()
	Ptr() unsafe.Pointer
}
