// Code generated by ffmpeggen. DO NOT EDIT.

package in

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// SwresampleContext is the public interface for swresample domain operations.
type SwresampleContext interface {
	Alloc() unsafe.Pointer
	Init(s unsafe.Pointer) int32
	Convert(s unsafe.Pointer, out unsafe.Pointer, outCount int32, in unsafe.Pointer, inCount int32) int32
	FreePtr(s unsafe.Pointer)
	Free()
	Ptr() unsafe.Pointer
}
