// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import is used

type formatCAPIAdapter struct{}

func (formatCAPIAdapter) AllocContext() unsafe.Pointer {
	return avformat_alloc_context()
}

func (formatCAPIAdapter) FreeContext(s unsafe.Pointer) {
	avformat_free_context(s)
}

func (formatCAPIAdapter) OpenInput(ps unsafe.Pointer, uRL *byte, fmt unsafe.Pointer, options unsafe.Pointer) int32 {
	return avformat_open_input(ps, uRL, fmt, options)
}

func (formatCAPIAdapter) FindStreamInfo(ic unsafe.Pointer, options unsafe.Pointer) int32 {
	return avformat_find_stream_info(ic, options)
}

func (formatCAPIAdapter) ReadFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return av_read_frame(s, pkt)
}

func (formatCAPIAdapter) CloseInput(s unsafe.Pointer) {
	avformat_close_input(s)
}

func (formatCAPIAdapter) AllocOutputContext2(ctx unsafe.Pointer, oformat unsafe.Pointer, formatName *byte, filename *byte) int32 {
	return avformat_alloc_output_context2(ctx, oformat, formatName, filename)
}

func (formatCAPIAdapter) NewStream(s unsafe.Pointer, c unsafe.Pointer) unsafe.Pointer {
	return avformat_new_stream(s, c)
}

func (formatCAPIAdapter) WriteHeader(s unsafe.Pointer, options unsafe.Pointer) int32 {
	return avformat_write_header(s, options)
}

func (formatCAPIAdapter) InterleavedWriteFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return av_interleaved_write_frame(s, pkt)
}

func (formatCAPIAdapter) WriteTrailer(s unsafe.Pointer) int32 {
	return av_write_trailer(s)
}

type codecCAPIAdapter struct{}

func (codecCAPIAdapter) FindDecoder(iD int32) unsafe.Pointer {
	return avcodec_find_decoder(iD)
}

func (codecCAPIAdapter) FindEncoder(iD int32) unsafe.Pointer {
	return avcodec_find_encoder(iD)
}

func (codecCAPIAdapter) FindDecoderByName(name *byte) unsafe.Pointer {
	return avcodec_find_decoder_by_name(name)
}

func (codecCAPIAdapter) FindEncoderByName(name *byte) unsafe.Pointer {
	return avcodec_find_encoder_by_name(name)
}

func (codecCAPIAdapter) AllocContext3(codec unsafe.Pointer) unsafe.Pointer {
	return avcodec_alloc_context3(codec)
}

func (codecCAPIAdapter) FreeContext(avctx unsafe.Pointer) {
	avcodec_free_context(avctx)
}

func (codecCAPIAdapter) Open2(avctx unsafe.Pointer, codec unsafe.Pointer, options unsafe.Pointer) int32 {
	return avcodec_open2(avctx, codec, options)
}

func (codecCAPIAdapter) SendPacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return avcodec_send_packet(avctx, avpkt)
}

func (codecCAPIAdapter) ReceiveFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return avcodec_receive_frame(avctx, frame)
}

func (codecCAPIAdapter) SendFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return avcodec_send_frame(avctx, frame)
}

func (codecCAPIAdapter) ReceivePacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return avcodec_receive_packet(avctx, avpkt)
}

func (codecCAPIAdapter) ParametersToContext(codec unsafe.Pointer, par unsafe.Pointer) int32 {
	return avcodec_parameters_to_context(codec, par)
}

func (codecCAPIAdapter) ParametersFromContext(par unsafe.Pointer, codec unsafe.Pointer) int32 {
	return avcodec_parameters_from_context(par, codec)
}

type packetCAPIAdapter struct{}

func (packetCAPIAdapter) Alloc() unsafe.Pointer {
	return av_packet_alloc()
}

func (packetCAPIAdapter) FreePtr(pkt unsafe.Pointer) {
	av_packet_free(pkt)
}

func (packetCAPIAdapter) Unref(pkt unsafe.Pointer) {
	av_packet_unref(pkt)
}

func (packetCAPIAdapter) Ref(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return av_packet_ref(dst, src)
}

func (packetCAPIAdapter) RescaleTs(pkt unsafe.Pointer, tbSrc AVRational, tbDst AVRational) {
	av_packet_rescale_ts(pkt, tbSrc, tbDst)
}

type frameCAPIAdapter struct{}

func (frameCAPIAdapter) Alloc() unsafe.Pointer {
	return av_frame_alloc()
}

func (frameCAPIAdapter) FreePtr(frame unsafe.Pointer) {
	av_frame_free(frame)
}

func (frameCAPIAdapter) Unref(frame unsafe.Pointer) {
	av_frame_unref(frame)
}

func (frameCAPIAdapter) Ref(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return av_frame_ref(dst, src)
}

func (frameCAPIAdapter) Clone(src unsafe.Pointer) unsafe.Pointer {
	return av_frame_clone(src)
}

func (frameCAPIAdapter) GetBuffer(frame unsafe.Pointer, align int32) int32 {
	return av_frame_get_buffer(frame, align)
}

func (frameCAPIAdapter) IsWritable(frame unsafe.Pointer) int32 {
	return av_frame_is_writable(frame)
}

func (frameCAPIAdapter) MakeWritable(frame unsafe.Pointer) int32 {
	return av_frame_make_writable(frame)
}

type swscaleCAPIAdapter struct{}

func (swscaleCAPIAdapter) GetContext(srcw int32, srch int32, srcformat int32, dstw int32, dsth int32, dstformat int32, flags int32, srcfilter unsafe.Pointer, dstfilter unsafe.Pointer, param unsafe.Pointer) unsafe.Pointer {
	return sws_getContext(srcw, srch, srcformat, dstw, dsth, dstformat, flags, srcfilter, dstfilter, param)
}

func (swscaleCAPIAdapter) Scale(c unsafe.Pointer, srcslice unsafe.Pointer, srcstride int32, srcslicey int32, srcsliceh int32, dst unsafe.Pointer, dststride int32) int32 {
	return sws_scale(c, srcslice, srcstride, srcslicey, srcsliceh, dst, dststride)
}

func (swscaleCAPIAdapter) FreeContext(swscontext unsafe.Pointer) {
	sws_freeContext(swscontext)
}

type swresampleCAPIAdapter struct{}

func (swresampleCAPIAdapter) Alloc() unsafe.Pointer {
	return swr_alloc()
}

func (swresampleCAPIAdapter) Init(s unsafe.Pointer) int32 {
	return swr_init(s)
}

func (swresampleCAPIAdapter) Convert(s unsafe.Pointer, out unsafe.Pointer, outCount int32, in unsafe.Pointer, inCount int32) int32 {
	return swr_convert(s, out, outCount, in, inCount)
}

func (swresampleCAPIAdapter) FreePtr(s unsafe.Pointer) {
	swr_free(s)
}

type dictCAPIAdapter struct{}

func (dictCAPIAdapter) Get(m unsafe.Pointer, key *byte, prev unsafe.Pointer, flags int32) unsafe.Pointer {
	return av_dict_get(m, key, prev, flags)
}

func (dictCAPIAdapter) Set(pm unsafe.Pointer, key *byte, value *byte, flags int32) int32 {
	return av_dict_set(pm, key, value, flags)
}

func (dictCAPIAdapter) FreePtr(m unsafe.Pointer) {
	av_dict_free(m)
}

func (dictCAPIAdapter) Count(m unsafe.Pointer) int32 {
	return av_dict_count(m)
}

type utilCAPIAdapter struct{}

func (utilCAPIAdapter) Malloc(size uintptr) unsafe.Pointer {
	return av_malloc(size)
}

func (utilCAPIAdapter) Free(ptr unsafe.Pointer) {
	av_free(ptr)
}

func (utilCAPIAdapter) OptSet(obj unsafe.Pointer, name *byte, val *byte, searchFlags int32) int32 {
	return av_opt_set(obj, name, val, searchFlags)
}

func (utilCAPIAdapter) OptSetInt(obj unsafe.Pointer, name *byte, val int64, searchFlags int32) int32 {
	return av_opt_set_int(obj, name, val, searchFlags)
}

func (utilCAPIAdapter) LogSetLevel(level int32) {
	av_log_set_level(level)
}

func (utilCAPIAdapter) LogGetLevel() int32 {
	return av_log_get_level()
}

func (utilCAPIAdapter) RescaleQ(a int64, bq AVRational, cq AVRational) int64 {
	return av_rescale_q(a, bq, cq)
}

func (utilCAPIAdapter) ImageGetBufferSize(pixFmt int32, width int32, height int32, align int32) int32 {
	return av_image_get_buffer_size(pixFmt, width, height, align)
}

func (utilCAPIAdapter) Strerror(errnum int32, errbuf *byte, errbufSize uintptr) int32 {
	return av_strerror(errnum, errbuf, errbufSize)
}

// Adapters provides the real CAPI implementations.
type Adapters struct {
	Format     out.FormatCAPI
	Codec      out.CodecCAPI
	Packet     out.PacketCAPI
	Frame      out.FrameCAPI
	Swscale    out.SwscaleCAPI
	Swresample out.SwresampleCAPI
	Dict       out.DictCAPI
	Util       out.UtilCAPI
}

// NewAdapters returns Adapters wired to real purego bindings.
func NewAdapters() Adapters {
	return Adapters{
		Format:     formatCAPIAdapter{},
		Codec:      codecCAPIAdapter{},
		Packet:     packetCAPIAdapter{},
		Frame:      frameCAPIAdapter{},
		Swscale:    swscaleCAPIAdapter{},
		Swresample: swresampleCAPIAdapter{},
		Dict:       dictCAPIAdapter{},
		Util:       utilCAPIAdapter{},
	}
}
