// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for avfilter domain.
var (
	avfilter_graph_alloc         func() unsafe.Pointer
	avfilter_graph_free          func(unsafe.Pointer)
	avfilter_graph_create_filter func(unsafe.Pointer, unsafe.Pointer, *byte, *byte, unsafe.Pointer, unsafe.Pointer) int32
	avfilter_graph_parse_ptr     func(unsafe.Pointer, *byte, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) int32
	avfilter_graph_config        func(unsafe.Pointer, unsafe.Pointer) int32
	avfilter_get_by_name         func(*byte) unsafe.Pointer
	av_buffersrc_add_frame_flags func(unsafe.Pointer, unsafe.Pointer, int32) int32
	av_buffersink_get_frame      func(unsafe.Pointer, unsafe.Pointer) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterAvfilter registers all avfilter domain purego symbols.
func RegisterAvfilter(handle uintptr) {
	purego.RegisterLibFunc(&avfilter_graph_alloc, handle, "avfilter_graph_alloc")
	purego.RegisterLibFunc(&avfilter_graph_free, handle, "avfilter_graph_free")
	purego.RegisterLibFunc(&avfilter_graph_create_filter, handle, "avfilter_graph_create_filter")
	purego.RegisterLibFunc(&avfilter_graph_parse_ptr, handle, "avfilter_graph_parse_ptr")
	purego.RegisterLibFunc(&avfilter_graph_config, handle, "avfilter_graph_config")
	purego.RegisterLibFunc(&avfilter_get_by_name, handle, "avfilter_get_by_name")
	purego.RegisterLibFunc(&av_buffersrc_add_frame_flags, handle, "av_buffersrc_add_frame_flags")
	purego.RegisterLibFunc(&av_buffersink_get_frame, handle, "av_buffersink_get_frame")
}
