// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import "unsafe"

// purego function pointer variables for codec domain.
var (
	avcodec_find_decoder            func(int32) unsafe.Pointer
	avcodec_find_encoder            func(int32) unsafe.Pointer
	avcodec_find_decoder_by_name    func(*byte) unsafe.Pointer
	avcodec_find_encoder_by_name    func(*byte) unsafe.Pointer
	avcodec_alloc_context3          func(unsafe.Pointer) unsafe.Pointer
	avcodec_free_context            func(unsafe.Pointer)
	avcodec_open2                   func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) int32
	avcodec_send_packet             func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_receive_frame           func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_send_frame              func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_receive_packet          func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_parameters_to_context   func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_parameters_from_context func(unsafe.Pointer, unsafe.Pointer) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// Offset constants for struct field accessors.
const (
	OffsetAVCodecContextCodecType    = 12
	OffsetAVCodecContextCodecID      = 24
	OffsetAVCodecContextTimeBase     = 84
	OffsetAVCodecContextWidth        = 112
	OffsetAVCodecContextHeight       = 116
	OffsetAVCodecContextPixelFormat  = 136
	OffsetAVCodecContextSampleRate   = 344
	OffsetAVCodecContextSampleFormat = 348
	OffsetAVCodecContextHWDeviceCtx  = 560
	OffsetAVCodecContextHWFramesCtx  = 552
)

// RegisterCodec registers all codec domain purego symbols.
func RegisterCodec(handle uintptr) {
	tryRegisterLibFunc(&avcodec_find_decoder, handle, "avcodec_find_decoder")
	tryRegisterLibFunc(&avcodec_find_encoder, handle, "avcodec_find_encoder")
	tryRegisterLibFunc(&avcodec_find_decoder_by_name, handle, "avcodec_find_decoder_by_name")
	tryRegisterLibFunc(&avcodec_find_encoder_by_name, handle, "avcodec_find_encoder_by_name")
	tryRegisterLibFunc(&avcodec_alloc_context3, handle, "avcodec_alloc_context3")
	tryRegisterLibFunc(&avcodec_free_context, handle, "avcodec_free_context")
	tryRegisterLibFunc(&avcodec_open2, handle, "avcodec_open2")
	tryRegisterLibFunc(&avcodec_send_packet, handle, "avcodec_send_packet")
	tryRegisterLibFunc(&avcodec_receive_frame, handle, "avcodec_receive_frame")
	tryRegisterLibFunc(&avcodec_send_frame, handle, "avcodec_send_frame")
	tryRegisterLibFunc(&avcodec_receive_packet, handle, "avcodec_receive_packet")
	tryRegisterLibFunc(&avcodec_parameters_to_context, handle, "avcodec_parameters_to_context")
	tryRegisterLibFunc(&avcodec_parameters_from_context, handle, "avcodec_parameters_from_context")
}
