// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for codec domain.
var (
	avcodec_find_decoder            func(int32) unsafe.Pointer
	avcodec_find_encoder            func(int32) unsafe.Pointer
	avcodec_find_decoder_by_name    func(*byte) unsafe.Pointer
	avcodec_find_encoder_by_name    func(*byte) unsafe.Pointer
	avcodec_alloc_context3          func(unsafe.Pointer) unsafe.Pointer
	avcodec_free_context            func(unsafe.Pointer)
	avcodec_open2                   func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) int32
	avcodec_send_packet             func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_receive_frame           func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_send_frame              func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_receive_packet          func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_parameters_to_context   func(unsafe.Pointer, unsafe.Pointer) int32
	avcodec_parameters_from_context func(unsafe.Pointer, unsafe.Pointer) int32
)

// Offset constants for struct field accessors.
const (
	OffsetAVCodecContextWidth       = 112
	OffsetAVCodecContextHeight      = 116
	OffsetAVCodecContextPixelFormat = 80
	OffsetAVCodecContextSampleRate  = 156
	OffsetAVCodecContextTimeBase    = 40
)

// RegisterCodec registers all codec domain purego symbols.
func RegisterCodec(handle uintptr) {
	purego.RegisterLibFunc(&avcodec_find_decoder, handle, "avcodec_find_decoder")
	purego.RegisterLibFunc(&avcodec_find_encoder, handle, "avcodec_find_encoder")
	purego.RegisterLibFunc(&avcodec_find_decoder_by_name, handle, "avcodec_find_decoder_by_name")
	purego.RegisterLibFunc(&avcodec_find_encoder_by_name, handle, "avcodec_find_encoder_by_name")
	purego.RegisterLibFunc(&avcodec_alloc_context3, handle, "avcodec_alloc_context3")
	purego.RegisterLibFunc(&avcodec_free_context, handle, "avcodec_free_context")
	purego.RegisterLibFunc(&avcodec_open2, handle, "avcodec_open2")
	purego.RegisterLibFunc(&avcodec_send_packet, handle, "avcodec_send_packet")
	purego.RegisterLibFunc(&avcodec_receive_frame, handle, "avcodec_receive_frame")
	purego.RegisterLibFunc(&avcodec_send_frame, handle, "avcodec_send_frame")
	purego.RegisterLibFunc(&avcodec_receive_packet, handle, "avcodec_receive_packet")
	purego.RegisterLibFunc(&avcodec_parameters_to_context, handle, "avcodec_parameters_to_context")
	purego.RegisterLibFunc(&avcodec_parameters_from_context, handle, "avcodec_parameters_from_context")
}
