// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import "unsafe"

// purego function pointer variables for dict domain.
var (
	av_dict_get   func(unsafe.Pointer, *byte, unsafe.Pointer, int32) unsafe.Pointer
	av_dict_set   func(unsafe.Pointer, *byte, *byte, int32) int32
	av_dict_free  func(unsafe.Pointer)
	av_dict_count func(unsafe.Pointer) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterDict registers all dict domain purego symbols.
func RegisterDict(handle uintptr) {
	tryRegisterLibFunc(&av_dict_get, handle, "av_dict_get")
	tryRegisterLibFunc(&av_dict_set, handle, "av_dict_set")
	tryRegisterLibFunc(&av_dict_free, handle, "av_dict_free")
	tryRegisterLibFunc(&av_dict_count, handle, "av_dict_count")
}
