// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import "unsafe"

// purego function pointer variables for format domain.
var (
	avformat_alloc_context         func() unsafe.Pointer
	avformat_free_context          func(unsafe.Pointer)
	avformat_open_input            func(unsafe.Pointer, *byte, unsafe.Pointer, unsafe.Pointer) int32
	avformat_find_stream_info      func(unsafe.Pointer, unsafe.Pointer) int32
	av_read_frame                  func(unsafe.Pointer, unsafe.Pointer) int32
	avformat_close_input           func(unsafe.Pointer)
	avformat_alloc_output_context2 func(unsafe.Pointer, unsafe.Pointer, *byte, *byte) int32
	avformat_new_stream            func(unsafe.Pointer, unsafe.Pointer) unsafe.Pointer
	avformat_write_header          func(unsafe.Pointer, unsafe.Pointer) int32
	av_interleaved_write_frame     func(unsafe.Pointer, unsafe.Pointer) int32
	av_write_trailer               func(unsafe.Pointer) int32
	avio_alloc_context             func(int32, int32, unsafe.Pointer, uintptr, uintptr, uintptr) unsafe.Pointer
	avio_context_free              func(unsafe.Pointer)
)

var _ = unsafe.Pointer(nil) // ensure import

// Offset constants for struct field accessors.
const (
	OffsetAVFormatContextNbStreams  = 44
	OffsetAVFormatContextStreamsPtr = 48
	OffsetAVFormatContextDuration   = 104
	OffsetAVFormatContextBitRate    = 112
	OffsetAVFormatContextPB         = 32
	OffsetAVFormatContextFlags      = 128
)

// RegisterFormat registers all format domain purego symbols.
func RegisterFormat(handle uintptr) {
	tryRegisterLibFunc(&avformat_alloc_context, handle, "avformat_alloc_context")
	tryRegisterLibFunc(&avformat_free_context, handle, "avformat_free_context")
	tryRegisterLibFunc(&avformat_open_input, handle, "avformat_open_input")
	tryRegisterLibFunc(&avformat_find_stream_info, handle, "avformat_find_stream_info")
	tryRegisterLibFunc(&av_read_frame, handle, "av_read_frame")
	tryRegisterLibFunc(&avformat_close_input, handle, "avformat_close_input")
	tryRegisterLibFunc(&avformat_alloc_output_context2, handle, "avformat_alloc_output_context2")
	tryRegisterLibFunc(&avformat_new_stream, handle, "avformat_new_stream")
	tryRegisterLibFunc(&avformat_write_header, handle, "avformat_write_header")
	tryRegisterLibFunc(&av_interleaved_write_frame, handle, "av_interleaved_write_frame")
	tryRegisterLibFunc(&av_write_trailer, handle, "av_write_trailer")
	tryRegisterLibFunc(&avio_alloc_context, handle, "avio_alloc_context")
	tryRegisterLibFunc(&avio_context_free, handle, "avio_context_free")
}
