// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for format domain.
var (
	avformat_alloc_context         func() unsafe.Pointer
	avformat_free_context          func(unsafe.Pointer)
	avformat_open_input            func(unsafe.Pointer, *byte, unsafe.Pointer, unsafe.Pointer) int32
	avformat_find_stream_info      func(unsafe.Pointer, unsafe.Pointer) int32
	av_read_frame                  func(unsafe.Pointer, unsafe.Pointer) int32
	avformat_close_input           func(unsafe.Pointer)
	avformat_alloc_output_context2 func(unsafe.Pointer, unsafe.Pointer, *byte, *byte) int32
	avformat_new_stream            func(unsafe.Pointer, unsafe.Pointer) unsafe.Pointer
	avformat_write_header          func(unsafe.Pointer, unsafe.Pointer) int32
	av_interleaved_write_frame     func(unsafe.Pointer, unsafe.Pointer) int32
	av_write_trailer               func(unsafe.Pointer) int32
)

// Offset constants for struct field accessors.
const (
	OffsetAVFormatContextNbStreams = 44
	OffsetAVStreamIndex            = 0
	OffsetAVStreamCodecParameters  = 8
	OffsetAVStreamTimeBase         = 16
)

// RegisterFormat registers all format domain purego symbols.
func RegisterFormat(handle uintptr) {
	purego.RegisterLibFunc(&avformat_alloc_context, handle, "avformat_alloc_context")
	purego.RegisterLibFunc(&avformat_free_context, handle, "avformat_free_context")
	purego.RegisterLibFunc(&avformat_open_input, handle, "avformat_open_input")
	purego.RegisterLibFunc(&avformat_find_stream_info, handle, "avformat_find_stream_info")
	purego.RegisterLibFunc(&av_read_frame, handle, "av_read_frame")
	purego.RegisterLibFunc(&avformat_close_input, handle, "avformat_close_input")
	purego.RegisterLibFunc(&avformat_alloc_output_context2, handle, "avformat_alloc_output_context2")
	purego.RegisterLibFunc(&avformat_new_stream, handle, "avformat_new_stream")
	purego.RegisterLibFunc(&avformat_write_header, handle, "avformat_write_header")
	purego.RegisterLibFunc(&av_interleaved_write_frame, handle, "av_interleaved_write_frame")
	purego.RegisterLibFunc(&av_write_trailer, handle, "av_write_trailer")
}
