// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for frame domain.
var (
	av_frame_alloc         func() unsafe.Pointer
	av_frame_free          func(unsafe.Pointer)
	av_frame_unref         func(unsafe.Pointer)
	av_frame_ref           func(unsafe.Pointer, unsafe.Pointer) int32
	av_frame_clone         func(unsafe.Pointer) unsafe.Pointer
	av_frame_get_buffer    func(unsafe.Pointer, int32) int32
	av_frame_is_writable   func(unsafe.Pointer) int32
	av_frame_make_writable func(unsafe.Pointer) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// Offset constants for struct field accessors.
const (
	OffsetAVFrameDataPtr     = 0
	OffsetAVFrameLinesizePtr = 64
	OffsetAVFrameWidth       = 104
	OffsetAVFrameHeight      = 108
	OffsetAVFrameNbSamples   = 112
	OffsetAVFrameFormat      = 116
	OffsetAVFramePts         = 136
	OffsetAVFramePktDts      = 144
	OffsetAVFrameSampleRate  = 180
	OffsetAVFrameHWFramesCtx = 328
)

// RegisterFrame registers all frame domain purego symbols.
func RegisterFrame(handle uintptr) {
	purego.RegisterLibFunc(&av_frame_alloc, handle, "av_frame_alloc")
	purego.RegisterLibFunc(&av_frame_free, handle, "av_frame_free")
	purego.RegisterLibFunc(&av_frame_unref, handle, "av_frame_unref")
	purego.RegisterLibFunc(&av_frame_ref, handle, "av_frame_ref")
	purego.RegisterLibFunc(&av_frame_clone, handle, "av_frame_clone")
	purego.RegisterLibFunc(&av_frame_get_buffer, handle, "av_frame_get_buffer")
	purego.RegisterLibFunc(&av_frame_is_writable, handle, "av_frame_is_writable")
	purego.RegisterLibFunc(&av_frame_make_writable, handle, "av_frame_make_writable")
}
