// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for hwaccel domain.
var (
	av_hwdevice_ctx_create        func(unsafe.Pointer, int32, *byte, unsafe.Pointer, int32) int32
	av_hwdevice_find_type_by_name func(*byte) int32
	av_hwframe_transfer_data      func(unsafe.Pointer, unsafe.Pointer, int32) int32
	av_hwdevice_iterate_types     func(int32) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterHwaccel registers all hwaccel domain purego symbols.
func RegisterHwaccel(handle uintptr) {
	purego.RegisterLibFunc(&av_hwdevice_ctx_create, handle, "av_hwdevice_ctx_create")
	purego.RegisterLibFunc(&av_hwdevice_find_type_by_name, handle, "av_hwdevice_find_type_by_name")
	purego.RegisterLibFunc(&av_hwframe_transfer_data, handle, "av_hwframe_transfer_data")
	purego.RegisterLibFunc(&av_hwdevice_iterate_types, handle, "av_hwdevice_iterate_types")
}
