// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for packet domain.
var (
	av_packet_alloc      func() unsafe.Pointer
	av_packet_free       func(unsafe.Pointer)
	av_packet_unref      func(unsafe.Pointer)
	av_packet_ref        func(unsafe.Pointer, unsafe.Pointer) int32
	av_packet_rescale_ts func(unsafe.Pointer, AVRational, AVRational)
)

// RegisterPacket registers all packet domain purego symbols.
func RegisterPacket(handle uintptr) {
	purego.RegisterLibFunc(&av_packet_alloc, handle, "av_packet_alloc")
	purego.RegisterLibFunc(&av_packet_free, handle, "av_packet_free")
	purego.RegisterLibFunc(&av_packet_unref, handle, "av_packet_unref")
	purego.RegisterLibFunc(&av_packet_ref, handle, "av_packet_ref")
	purego.RegisterLibFunc(&av_packet_rescale_ts, handle, "av_packet_rescale_ts")
}
