// Code generated by ffmpeggen. DO NOT EDIT.

package capi

// Handles holds all FFmpeg shared library handles.
type Handles struct {
	Avutil     uintptr
	Avcodec    uintptr
	Avformat   uintptr
	Swscale    uintptr
	Swresample uintptr
	Avfilter   uintptr
}

// Register loads all FFmpeg C API symbols from the shared library handles.
func Register(h Handles) {
	RegisterFrame(h.Avutil)
	RegisterDict(h.Avutil)
	RegisterUtil(h.Avutil)
	RegisterHwaccel(h.Avutil)
	RegisterCodec(h.Avcodec)
	RegisterPacket(h.Avcodec)
	RegisterFormat(h.Avformat)
	RegisterSwscale(h.Swscale)
	RegisterSwresample(h.Swresample)
	RegisterAvfilter(h.Avfilter)
}
