// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import "unsafe"

var _ = unsafe.Pointer(nil) // ensure import

// Offset constants for struct field accessors.
const (
	OffsetAVStreamIndex           = 8
	OffsetAVStreamCodecParameters = 16
	OffsetAVStreamTimeBase        = 32
	OffsetAVStreamDuration        = 48
	OffsetAVStreamNbFrames        = 56
)
