// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for swresample domain.
var (
	swr_alloc   func() unsafe.Pointer
	swr_init    func(unsafe.Pointer) int32
	swr_convert func(unsafe.Pointer, unsafe.Pointer, int32, unsafe.Pointer, int32) int32
	swr_free    func(unsafe.Pointer)
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterSwresample registers all swresample domain purego symbols.
func RegisterSwresample(handle uintptr) {
	purego.RegisterLibFunc(&swr_alloc, handle, "swr_alloc")
	purego.RegisterLibFunc(&swr_init, handle, "swr_init")
	purego.RegisterLibFunc(&swr_convert, handle, "swr_convert")
	purego.RegisterLibFunc(&swr_free, handle, "swr_free")
}
