// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import "unsafe"

// purego function pointer variables for swscale domain.
var (
	sws_getContext  func(int32, int32, int32, int32, int32, int32, int32, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) unsafe.Pointer
	sws_scale       func(unsafe.Pointer, unsafe.Pointer, int32, int32, int32, unsafe.Pointer, int32) int32
	sws_freeContext func(unsafe.Pointer)
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterSwscale registers all swscale domain purego symbols.
func RegisterSwscale(handle uintptr) {
	tryRegisterLibFunc(&sws_getContext, handle, "sws_getContext")
	tryRegisterLibFunc(&sws_scale, handle, "sws_scale")
	tryRegisterLibFunc(&sws_freeContext, handle, "sws_freeContext")
}
