// Code generated by ffmpeggen. DO NOT EDIT.

package capi

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// purego function pointer variables for util domain.
var (
	av_malloc                func(uintptr) unsafe.Pointer
	av_free                  func(unsafe.Pointer)
	av_opt_set               func(unsafe.Pointer, *byte, *byte, int32) int32
	av_opt_set_int           func(unsafe.Pointer, *byte, int64, int32) int32
	av_log_set_level         func(int32)
	av_log_get_level         func() int32
	av_rescale_q             func(int64, AVRational, AVRational) int64
	av_image_get_buffer_size func(int32, int32, int32, int32) int32
	av_strerror              func(int32, *byte, uintptr) int32
)

var _ = unsafe.Pointer(nil) // ensure import

// RegisterUtil registers all util domain purego symbols.
func RegisterUtil(handle uintptr) {
	purego.RegisterLibFunc(&av_malloc, handle, "av_malloc")
	purego.RegisterLibFunc(&av_free, handle, "av_free")
	purego.RegisterLibFunc(&av_opt_set, handle, "av_opt_set")
	purego.RegisterLibFunc(&av_opt_set_int, handle, "av_opt_set_int")
	purego.RegisterLibFunc(&av_log_set_level, handle, "av_log_set_level")
	purego.RegisterLibFunc(&av_log_get_level, handle, "av_log_get_level")
	purego.RegisterLibFunc(&av_rescale_q, handle, "av_rescale_q")
	purego.RegisterLibFunc(&av_image_get_buffer_size, handle, "av_image_get_buffer_size")
	purego.RegisterLibFunc(&av_strerror, handle, "av_strerror")
}
