// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// CodecAllocContext3 Allocate an AVCodecContext and set its fields to default values. The resulting struct should be freed with avcodec_free_context(). for the given codec. It is illegal to then call avcodec_open2() with a different codec. If NULL, then the codec-specific defaults won't be initialized, which may result in suboptimal default settings (this is important mainly for encoders, e.g. libx264). /
func CodecAllocContext3(codec unsafe.Pointer) unsafe.Pointer {
	return raw.AvcodecAllocContext3(codec)
}

func CodecFreeContext(avctx unsafe.Pointer) {
	raw.AvcodecFreeContext(avctx)
}

// CodecParametersFromContext Fill the parameters struct based on the values from the supplied codec context. Any allocated fields in par are freed and replaced with duplicates of the corresponding fields in codec. /
func CodecParametersFromContext(par unsafe.Pointer, codec unsafe.Pointer) int32 {
	return raw.AvcodecParametersFromContext(par, codec)
}

// CodecParametersToContext Fill the codec context based on the values from the supplied codec parameters. Any allocated fields in codec that have a corresponding field in par are freed and replaced with duplicates of the corresponding field in par. Fields in codec that do not have a counterpart in par are not touched. /
func CodecParametersToContext(codec unsafe.Pointer, par unsafe.Pointer) int32 {
	return raw.AvcodecParametersToContext(codec, par)
}

func CodecOpen2(avctx unsafe.Pointer, codec unsafe.Pointer, options unsafe.Pointer) int32 {
	return raw.AvcodecOpen2(avctx, codec, options)
}

func CodecSendPacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return raw.AvcodecSendPacket(avctx, avpkt)
}

func CodecReceiveFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return raw.AvcodecReceiveFrame(avctx, frame)
}

func CodecSendFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return raw.AvcodecSendFrame(avctx, frame)
}

func CodecReceivePacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return raw.AvcodecReceivePacket(avctx, avpkt)
}

func CodecFlushBuffers(avctx unsafe.Pointer) {
	raw.AvcodecFlushBuffers(avctx)
}

// CodecIsOpen 0 otherwise. /
func CodecIsOpen(s unsafe.Pointer) int32 {
	return raw.AvcodecIsOpen(s)
}
