// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.FilterCAPI        // ensure import
var _ = capi.Register       // ensure import

// FilterGraph is the public interface for avfilter domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type FilterGraph = in.FilterGraph

type avfilterWrapper struct {
	ptr  unsafe.Pointer
	capi out.FilterCAPI
}

// NewFilterGraphWithPtr wraps an existing pointer with FilterGraph methods.
func NewFilterGraphWithPtr(ptr unsafe.Pointer) *avfilterWrapper {
	return &avfilterWrapper{ptr: ptr, capi: defaultFilter()}
}

func (w *avfilterWrapper) GraphAlloc() unsafe.Pointer {
	return w.capi.GraphAlloc()
}

func (w *avfilterWrapper) GraphFree(graph unsafe.Pointer) {
	w.capi.GraphFree(graph)
}

func (w *avfilterWrapper) GraphCreateFilter(filtCtx unsafe.Pointer, filt unsafe.Pointer, name *byte, args *byte, opaque unsafe.Pointer, graphCtx unsafe.Pointer) int32 {
	return w.capi.GraphCreateFilter(filtCtx, filt, name, args, opaque, graphCtx)
}

func (w *avfilterWrapper) GraphParsePtr(graph unsafe.Pointer, filters *byte, inputs unsafe.Pointer, outputs unsafe.Pointer, logCtx unsafe.Pointer) int32 {
	return w.capi.GraphParsePtr(graph, filters, inputs, outputs, logCtx)
}

func (w *avfilterWrapper) GraphConfig(graphctx unsafe.Pointer, logCtx unsafe.Pointer) int32 {
	return w.capi.GraphConfig(graphctx, logCtx)
}

func (w *avfilterWrapper) GetByName(name *byte) unsafe.Pointer {
	return w.capi.GetByName(name)
}

func (w *avfilterWrapper) BuffersrcAddFrameFlags(bufferSrc unsafe.Pointer, frame unsafe.Pointer, flags int32) int32 {
	return w.capi.BuffersrcAddFrameFlags(bufferSrc, frame, flags)
}

func (w *avfilterWrapper) BuffersinkGetFrame(ctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return w.capi.BuffersinkGetFrame(ctx, frame)
}

func (w *avfilterWrapper) Free() {
	if w.ptr != nil {
		w.ptr = nil
	}
}

func (w *avfilterWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
