// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// OutputFormat /
type OutputFormat struct {
	ptr *raw.AVOutputFormat
}

func (w *OutputFormat) Raw() unsafe.Pointer {
	if w == nil {
		return nil
	}
	return unsafe.Pointer(w.ptr)
}

func (w *OutputFormat) Name() *byte {
	return w.ptr.Name
}

func (w *OutputFormat) LongName() *byte {
	return w.ptr.LongName
}

func (w *OutputFormat) MimeType() *byte {
	return w.ptr.MimeType
}

func (w *OutputFormat) Extensions() *byte {
	return w.ptr.Extensions
}

func (w *OutputFormat) Flags() int32 {
	return w.ptr.Flags
}

func (w *OutputFormat) CodecTag() unsafe.Pointer {
	return w.ptr.CodecTag
}

func (w *OutputFormat) PrivClass() unsafe.Pointer {
	return w.ptr.PrivClass
}

// InputFormat /
type InputFormat struct {
	ptr *raw.AVInputFormat
}

func (w *InputFormat) Raw() unsafe.Pointer {
	if w == nil {
		return nil
	}
	return unsafe.Pointer(w.ptr)
}

func (w *InputFormat) Name() *byte {
	return w.ptr.Name
}

func (w *InputFormat) LongName() *byte {
	return w.ptr.LongName
}

func (w *InputFormat) Flags() int32 {
	return w.ptr.Flags
}

func (w *InputFormat) Extensions() *byte {
	return w.ptr.Extensions
}

func (w *InputFormat) CodecTag() unsafe.Pointer {
	return w.ptr.CodecTag
}

func (w *InputFormat) PrivClass() unsafe.Pointer {
	return w.ptr.PrivClass
}

func (w *InputFormat) MimeType() *byte {
	return w.ptr.MimeType
}

// Stream Stream structure. New fields can be added to the end with minor version bumps. Removal, reordering and changes to existing fields require a major version bump. sizeof(AVStream) must not be used outside libav*. /
type Stream struct {
	ptr *raw.AVStream
}

func (w *Stream) Raw() unsafe.Pointer {
	if w == nil {
		return nil
	}
	return unsafe.Pointer(w.ptr)
}

func (w *Stream) AvClass() unsafe.Pointer {
	return w.ptr.AvClass
}

func (w *Stream) Index() int32 {
	return w.ptr.Index
}

func (w *Stream) ID() int32 {
	return w.ptr.ID
}

func (w *Stream) Codecpar() unsafe.Pointer {
	return w.ptr.Codecpar
}

func (w *Stream) PrivData() unsafe.Pointer {
	return w.ptr.PrivData
}

func (w *Stream) TimeBase() AVRational {
	return w.ptr.TimeBase
}

func (w *Stream) StartTime() int64 {
	return w.ptr.StartTime
}

func (w *Stream) Duration() int64 {
	return w.ptr.Duration
}

func (w *Stream) NbFrames() int64 {
	return w.ptr.NbFrames
}

func (w *Stream) Disposition() int32 {
	return w.ptr.Disposition
}

func (w *Stream) SampleAspectRatio() AVRational {
	return w.ptr.SampleAspectRatio
}

func (w *Stream) Metadata() unsafe.Pointer {
	return w.ptr.Metadata
}

func (w *Stream) AvgFrameRate() AVRational {
	return w.ptr.AvgFrameRate
}

func (w *Stream) AttachedPic() uintptr {
	return w.ptr.AttachedPic
}

func (w *Stream) EventFlags() int32 {
	return w.ptr.EventFlags
}

func (w *Stream) RFrameRate() AVRational {
	return w.ptr.RFrameRate
}

func (w *Stream) PTSWrapBits() int32 {
	return w.ptr.PTSWrapBits
}

// FormatVersion Return the LIBAVFORMAT_VERSION_INT constant. /
func FormatVersion() uint32 {
	return raw.AvformatVersion()
}

func FormatAllocContext() unsafe.Pointer {
	return raw.AvformatAllocContext()
}

func FormatFreeContext(s unsafe.Pointer) {
	raw.AvformatFreeContext(s)
}

func FormatNewStream(s unsafe.Pointer, c unsafe.Pointer) unsafe.Pointer {
	return raw.AvformatNewStream(s, c)
}

// FormatAllocOutputContext2 Allocate an AVFormatContext for an output format. avformat_free_context() can be used to free the context and everything allocated by the framework within it. or to NULL in case of failure format_name and filename are used instead context, if NULL filename is used instead context, may be NULL failure /
func FormatAllocOutputContext2(ctx unsafe.Pointer, oformat unsafe.Pointer, formatName string, filename string) int32 {
	formatNameC := cString(formatName)
	filenameC := cString(filename)
	return raw.AvformatAllocOutputContext2(ctx, oformat, formatNameC, filenameC)
}

func FormatOpenInput(ps unsafe.Pointer, uRL string, fmt unsafe.Pointer, options unsafe.Pointer) int32 {
	uRLC := cString(uRL)
	return raw.AvformatOpenInput(ps, uRLC, fmt, options)
}

func FormatFindStreamInfo(ic unsafe.Pointer, options unsafe.Pointer) int32 {
	return raw.AvformatFindStreamInfo(ic, options)
}

// FindBestStream Find the "best" stream in the file. The best stream is determined according to various heuristics as the most likely to be what the user expects. If the decoder parameter is non-NULL, av_find_best_stream will find the default decoder for the stream's codec; streams for which no decoder can be found are ignored. or -1 for automatic selection program) to this one, or -1 if none selected stream AVERROR_STREAM_NOT_FOUND if no stream with the requested type could be found, AVERROR_DECODER_NOT_FOUND if streams were found but no decoder NULL, then *decoder_ret is guaranteed to be set to a valid AVCodec. /
func FindBestStream(ic unsafe.Pointer, type_ int32, wantedStreamNb int32, relatedStream int32, decoderRet unsafe.Pointer, flags int32) int32 {
	return raw.AVFindBestStream(ic, type_, wantedStreamNb, relatedStream, decoderRet, flags)
}

func ReadFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return raw.AVReadFrame(s, pkt)
}

func FormatCloseInput(s unsafe.Pointer) {
	raw.AvformatCloseInput(s)
}

func FormatWriteHeader(s unsafe.Pointer, options unsafe.Pointer) int32 {
	return raw.AvformatWriteHeader(s, options)
}

func InterleavedWriteFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return raw.AVInterleavedWriteFrame(s, pkt)
}

func WriteTrailer(s unsafe.Pointer) int32 {
	return raw.AVWriteTrailer(s)
}
