// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"runtime"
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// AvioOpen Create and initialize a AVIOContext for accessing the resource indicated by url. read+write mode, the AVIOContext can be used only for writing. In case of failure the pointed to value is set to NULL. is to be opened AVERROR code in case of failure /
func AvioOpen(s unsafe.Pointer, uRL string, flags int32) int32 {
	uRLC, uRLBuf := cString(uRL)
	defer runtime.KeepAlive(uRLBuf)
	return raw.AvioOpen(s, uRLC, flags)
}

// AvioClosep Close the resource accessed by the AVIOContext *s, free it and set the pointer pointing to it to NULL. This function can only be used if s was opened by avio_open(). The internal buffer is automatically flushed before closing the resource. /
func AvioClosep(s unsafe.Pointer) int32 {
	return raw.AvioClosep(s)
}
