// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// MediaType /
type MediaType int32

const (
	MediaTypeAvmediaTypeUnknown    MediaType = -1
	MediaTypeAvmediaTypeVideo      MediaType = 0
	MediaTypeAvmediaTypeAudio      MediaType = 1
	MediaTypeAvmediaTypeData       MediaType = 2
	MediaTypeAvmediaTypeSubtitle   MediaType = 3
	MediaTypeAvmediaTypeAttachment MediaType = 4
	MediaTypeAvmediaTypeNb         MediaType = 5
)

// AvutilVersion Return the LIBAVUTIL_VERSION_INT constant. /
func AvutilVersion() uint32 {
	return raw.AvutilVersion()
}
