// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.CodecCAPI         // ensure import
var _ = capi.Register       // ensure import

// CodecContext is the public interface for codec domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type CodecContext = in.CodecContext

type codecWrapper struct {
	ptr  unsafe.Pointer
	capi out.CodecCAPI
}

// NewCodecContextWithPtr wraps an existing pointer with CodecContext methods.
func NewCodecContextWithPtr(ptr unsafe.Pointer) *codecWrapper {
	return &codecWrapper{ptr: ptr, capi: defaultCodec()}
}

func (w *codecWrapper) FindDecoder(id int32) unsafe.Pointer {
	return w.capi.FindDecoder(id)
}

func (w *codecWrapper) FindEncoder(id int32) unsafe.Pointer {
	return w.capi.FindEncoder(id)
}

func (w *codecWrapper) FindDecoderByName(name *byte) unsafe.Pointer {
	return w.capi.FindDecoderByName(name)
}

func (w *codecWrapper) FindEncoderByName(name *byte) unsafe.Pointer {
	return w.capi.FindEncoderByName(name)
}

func (w *codecWrapper) AllocContext3(codec unsafe.Pointer) unsafe.Pointer {
	return w.capi.AllocContext3(codec)
}

func (w *codecWrapper) FreeContext(avctx unsafe.Pointer) {
	w.capi.FreeContext(avctx)
}

func (w *codecWrapper) Open2(avctx unsafe.Pointer, codec unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.Open2(avctx, codec, options)
}

func (w *codecWrapper) SendPacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return w.capi.SendPacket(avctx, avpkt)
}

func (w *codecWrapper) ReceiveFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return w.capi.ReceiveFrame(avctx, frame)
}

func (w *codecWrapper) SendFrame(avctx unsafe.Pointer, frame unsafe.Pointer) int32 {
	return w.capi.SendFrame(avctx, frame)
}

func (w *codecWrapper) ReceivePacket(avctx unsafe.Pointer, avpkt unsafe.Pointer) int32 {
	return w.capi.ReceivePacket(avctx, avpkt)
}

func (w *codecWrapper) ParametersToContext(codec unsafe.Pointer, par unsafe.Pointer) int32 {
	return w.capi.ParametersToContext(codec, par)
}

func (w *codecWrapper) ParametersFromContext(par unsafe.Pointer, codec unsafe.Pointer) int32 {
	return w.capi.ParametersFromContext(par, codec)
}

func (w *codecWrapper) CodecType() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextCodecType))
}

func (w *codecWrapper) SetCodecType(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextCodecType)) = v
}

func (w *codecWrapper) CodecID() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextCodecID))
}

func (w *codecWrapper) SetCodecID(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextCodecID)) = v
}

func (w *codecWrapper) TimeBase() AVRational {
	return *(*AVRational)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextTimeBase))
}

func (w *codecWrapper) SetTimeBase(v AVRational) {
	*(*AVRational)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextTimeBase)) = v
}

func (w *codecWrapper) Width() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextWidth))
}

func (w *codecWrapper) SetWidth(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextWidth)) = v
}

func (w *codecWrapper) Height() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHeight))
}

func (w *codecWrapper) SetHeight(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHeight)) = v
}

func (w *codecWrapper) PixelFormat() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextPixelFormat))
}

func (w *codecWrapper) SetPixelFormat(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextPixelFormat)) = v
}

func (w *codecWrapper) SampleRate() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextSampleRate))
}

func (w *codecWrapper) SetSampleRate(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextSampleRate)) = v
}

func (w *codecWrapper) SampleFormat() int32 {
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextSampleFormat))
}

func (w *codecWrapper) SetSampleFormat(v int32) {
	*(*int32)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextSampleFormat)) = v
}

func (w *codecWrapper) HWDeviceCtx() unsafe.Pointer {
	return *(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHWDeviceCtx))
}

func (w *codecWrapper) SetHWDeviceCtx(v unsafe.Pointer) {
	*(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHWDeviceCtx)) = v
}

func (w *codecWrapper) HWFramesCtx() unsafe.Pointer {
	return *(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHWFramesCtx))
}

func (w *codecWrapper) SetHWFramesCtx(v unsafe.Pointer) {
	*(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVCodecContextHWFramesCtx)) = v
}

func (w *codecWrapper) Free() {
	if w.ptr != nil {
		w.capi.FreeContext(w.ptr)
		w.ptr = nil
	}
}

func (w *codecWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
