// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// CodecFindDecoder Find a registered decoder with a matching codec ID. /
func CodecFindDecoder(iD int32) unsafe.Pointer {
	return raw.AvcodecFindDecoder(iD)
}

// CodecFindDecoderByName Find a registered decoder with the specified name. /
func CodecFindDecoderByName(name string) unsafe.Pointer {
	nameC := cString(name)
	return raw.AvcodecFindDecoderByName(nameC)
}

// CodecFindEncoder Find a registered encoder with a matching codec ID. /
func CodecFindEncoder(iD int32) unsafe.Pointer {
	return raw.AvcodecFindEncoder(iD)
}

// CodecFindEncoderByName Find a registered encoder with the specified name. /
func CodecFindEncoderByName(name string) unsafe.Pointer {
	nameC := cString(name)
	return raw.AvcodecFindEncoderByName(nameC)
}
