// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.DictCAPI          // ensure import
var _ = capi.Register       // ensure import

// Dictionary is the public interface for dict domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type Dictionary = in.Dictionary

type dictWrapper struct {
	ptr  unsafe.Pointer
	capi out.DictCAPI
}

// NewDictionaryWithPtr wraps an existing pointer with Dictionary methods.
func NewDictionaryWithPtr(ptr unsafe.Pointer) *dictWrapper {
	return &dictWrapper{ptr: ptr, capi: defaultDict()}
}

func (w *dictWrapper) Get(m unsafe.Pointer, key *byte, prev unsafe.Pointer, flags int32) unsafe.Pointer {
	return w.capi.Get(m, key, prev, flags)
}

func (w *dictWrapper) Set(pm unsafe.Pointer, key *byte, value *byte, flags int32) int32 {
	return w.capi.Set(pm, key, value, flags)
}

func (w *dictWrapper) FreePtr(m unsafe.Pointer) {
	w.capi.FreePtr(m)
}

func (w *dictWrapper) Count(m unsafe.Pointer) int32 {
	return w.capi.Count(m)
}

func (w *dictWrapper) Free() {
	if w.ptr != nil {
		// NOTE: Some FFmpeg free functions (avcodec_free_context, av_packet_free,
		// av_frame_free, swr_free) take double pointers (Type**) in C. The purego
		// binding passes a single pointer. The C function may attempt to NULL the
		// caller's pointer, but since we nil w.ptr on the Go side, this is safe
		// for single-call usage. Do not call Free() concurrently.
		w.capi.FreePtr(w.ptr)
		w.ptr = nil
	}
}

func (w *dictWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
