// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// DictionaryEntry /
type DictionaryEntry struct {
	ptr *raw.AVDictionaryEntry
}

func (w *DictionaryEntry) Raw() unsafe.Pointer {
	if w == nil {
		return nil
	}
	return unsafe.Pointer(w.ptr)
}

func (w *DictionaryEntry) Key() *byte {
	return w.ptr.Key
}

func (w *DictionaryEntry) Value() *byte {
	return w.ptr.Value
}

func DictGet(m unsafe.Pointer, key string, prev unsafe.Pointer, flags int32) unsafe.Pointer {
	keyC := cString(key)
	return raw.AVDictGet(m, keyC, prev, flags)
}

// DictCount Get number of entries in dictionary. /
func DictCount(m unsafe.Pointer) int32 {
	return raw.AVDictCount(m)
}

func DictSet(pm unsafe.Pointer, key string, value string, flags int32) int32 {
	keyC := cString(key)
	valueC := cString(value)
	return raw.AVDictSet(pm, keyC, valueC, flags)
}

func DictFree(m unsafe.Pointer) {
	raw.AVDictFree(m)
}
