// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

func Strerror(errnum int32, errbuf string, errbufSize uintptr) int32 {
	errbufC := cString(errbuf)
	return raw.AVStrerror(errnum, errbufC, errbufSize)
}
