// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.FormatCAPI        // ensure import
var _ = capi.Register       // ensure import

// FormatContext is the public interface for format domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type FormatContext = in.FormatContext

type formatWrapper struct {
	ptr  unsafe.Pointer
	capi out.FormatCAPI
}

func (w *formatWrapper) AllocContext() unsafe.Pointer {
	return w.capi.AllocContext()
}

func (w *formatWrapper) FreeContext(s unsafe.Pointer) {
	w.capi.FreeContext(s)
}

func (w *formatWrapper) OpenInput(ps unsafe.Pointer, url *byte, fmt unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.OpenInput(ps, url, fmt, options)
}

func (w *formatWrapper) FindStreamInfo(ic unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.FindStreamInfo(ic, options)
}

func (w *formatWrapper) ReadFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return w.capi.ReadFrame(s, pkt)
}

func (w *formatWrapper) CloseInput(s unsafe.Pointer) {
	w.capi.CloseInput(s)
}

func (w *formatWrapper) AllocOutputContext2(ctx unsafe.Pointer, oformat unsafe.Pointer, formatName *byte, filename *byte) int32 {
	return w.capi.AllocOutputContext2(ctx, oformat, formatName, filename)
}

func (w *formatWrapper) NewStream(s unsafe.Pointer, c unsafe.Pointer) unsafe.Pointer {
	return w.capi.NewStream(s, c)
}

func (w *formatWrapper) WriteHeader(s unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.WriteHeader(s, options)
}

func (w *formatWrapper) InterleavedWriteFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return w.capi.InterleavedWriteFrame(s, pkt)
}

func (w *formatWrapper) WriteTrailer(s unsafe.Pointer) int32 {
	return w.capi.WriteTrailer(s)
}

func (w *formatWrapper) NbStreams() uint32 {
	return *(*uint32)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextNbStreams))
}

func (w *formatWrapper) SetNbStreams(v uint32) {
	*(*uint32)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextNbStreams)) = v
}

func (w *formatWrapper) Free() {
	if w.ptr != nil {
		w.capi.FreeContext(w.ptr)
		w.ptr = nil
	}
}

func (w *formatWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
