// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	portin "github.com/bnema/purego-ffmpeg/internal/ports/in"
	portout "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ portout.FormatCAPI    // ensure import
var _ = capi.Register       // ensure import

// FormatContext is the public interface for format domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type FormatContext = portin.FormatContext

type formatWrapper struct {
	ptr  unsafe.Pointer
	capi portout.FormatCAPI
}

// NewFormatContextWithPtr wraps an existing pointer with FormatContext methods.
func NewFormatContextWithPtr(ptr unsafe.Pointer) *formatWrapper {
	return &formatWrapper{ptr: ptr, capi: defaultFormat()}
}

// AllocFormatContext allocates and returns a new FormatContext.
// Unlike the raw AllocContext() method, this stores the pointer internally.
// Returns nil if the C allocation fails.
func AllocFormatContext() *formatWrapper {
	w := &formatWrapper{capi: defaultFormat()}
	w.ptr = w.capi.AllocContext()
	if w.ptr == nil {
		return nil
	}
	return w
}

func (w *formatWrapper) AllocContext() unsafe.Pointer {
	return w.capi.AllocContext()
}

func (w *formatWrapper) FreeContext(s unsafe.Pointer) {
	w.capi.FreeContext(s)
}

func (w *formatWrapper) OpenInput(ps unsafe.Pointer, url *byte, fmt unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.OpenInput(ps, url, fmt, options)
}

func (w *formatWrapper) FindStreamInfo(ic unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.FindStreamInfo(ic, options)
}

func (w *formatWrapper) ReadFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return w.capi.ReadFrame(s, pkt)
}

func (w *formatWrapper) CloseInput(s unsafe.Pointer) {
	w.capi.CloseInput(s)
}

func (w *formatWrapper) AllocOutputContext2(ctx unsafe.Pointer, oformat unsafe.Pointer, formatName *byte, filename *byte) int32 {
	return w.capi.AllocOutputContext2(ctx, oformat, formatName, filename)
}

func (w *formatWrapper) NewStream(s unsafe.Pointer, c unsafe.Pointer) unsafe.Pointer {
	return w.capi.NewStream(s, c)
}

func (w *formatWrapper) WriteHeader(s unsafe.Pointer, options unsafe.Pointer) int32 {
	return w.capi.WriteHeader(s, options)
}

func (w *formatWrapper) InterleavedWriteFrame(s unsafe.Pointer, pkt unsafe.Pointer) int32 {
	return w.capi.InterleavedWriteFrame(s, pkt)
}

func (w *formatWrapper) WriteTrailer(s unsafe.Pointer) int32 {
	return w.capi.WriteTrailer(s)
}

func (w *formatWrapper) NbStreams() uint32 {
	if w.ptr == nil {
		var zero uint32
		return zero
	}
	return *(*uint32)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextNbStreams))
}

func (w *formatWrapper) StreamsPtr() unsafe.Pointer {
	if w.ptr == nil {
		var zero unsafe.Pointer
		return zero
	}
	return *(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextStreamsPtr))
}

func (w *formatWrapper) Duration() int64 {
	if w.ptr == nil {
		var zero int64
		return zero
	}
	return *(*int64)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextDuration))
}

func (w *formatWrapper) BitRate() int64 {
	if w.ptr == nil {
		var zero int64
		return zero
	}
	return *(*int64)(unsafe.Add(w.ptr, capi.OffsetAVFormatContextBitRate))
}

func (w *formatWrapper) Free() {
	if w.ptr != nil {
		// NOTE: Some FFmpeg free functions (avcodec_free_context, av_packet_free,
		// av_frame_free, swr_free) take double pointers (Type**) in C. The purego
		// binding passes a single pointer. The C function may attempt to NULL the
		// caller's pointer, but since we nil w.ptr on the Go side, this is safe
		// for single-call usage. Do not call Free() concurrently.
		w.capi.FreeContext(w.ptr)
		w.ptr = nil
	}
}

func (w *formatWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
