// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

type FrameSideDataType int32

const (
	FrameSideDataTypeFrameDataPanscan                   FrameSideDataType = 0
	FrameSideDataTypeFrameDataA53Cc                     FrameSideDataType = 1
	FrameSideDataTypeFrameDataStereo3d                  FrameSideDataType = 2
	FrameSideDataTypeFrameDataMatrixencoding            FrameSideDataType = 3
	FrameSideDataTypeFrameDataDownmixInfo               FrameSideDataType = 4
	FrameSideDataTypeFrameDataReplaygain                FrameSideDataType = 5
	FrameSideDataTypeFrameDataDisplaymatrix             FrameSideDataType = 6
	FrameSideDataTypeFrameDataAfd                       FrameSideDataType = 7
	FrameSideDataTypeFrameDataMotionVectors             FrameSideDataType = 8
	FrameSideDataTypeFrameDataSkipSamples               FrameSideDataType = 9
	FrameSideDataTypeFrameDataAudioServiceType          FrameSideDataType = 10
	FrameSideDataTypeFrameDataMasteringDisplayMetadata  FrameSideDataType = 11
	FrameSideDataTypeFrameDataGopTimecode               FrameSideDataType = 12
	FrameSideDataTypeFrameDataSpherical                 FrameSideDataType = 13
	FrameSideDataTypeFrameDataContentLightLevel         FrameSideDataType = 14
	FrameSideDataTypeFrameDataIccProfile                FrameSideDataType = 15
	FrameSideDataTypeFrameDataS12mTimecode              FrameSideDataType = 16
	FrameSideDataTypeFrameDataDynamicHdrPlus            FrameSideDataType = 17
	FrameSideDataTypeFrameDataRegionsOfInterest         FrameSideDataType = 18
	FrameSideDataTypeFrameDataVideoEncParams            FrameSideDataType = 19
	FrameSideDataTypeFrameDataSeiUnregistered           FrameSideDataType = 20
	FrameSideDataTypeFrameDataFilmGrainParams           FrameSideDataType = 21
	FrameSideDataTypeFrameDataDetectionBboxes           FrameSideDataType = 22
	FrameSideDataTypeFrameDataDoviRpuBuffer             FrameSideDataType = 23
	FrameSideDataTypeFrameDataDoviMetadata              FrameSideDataType = 24
	FrameSideDataTypeFrameDataDynamicHdrVivid           FrameSideDataType = 25
	FrameSideDataTypeFrameDataAmbientViewingEnvironment FrameSideDataType = 26
	FrameSideDataTypeFrameDataVideoHint                 FrameSideDataType = 27
	FrameSideDataTypeFrameDataLcevc                     FrameSideDataType = 28
	FrameSideDataTypeFrameDataViewID                    FrameSideDataType = 29
	FrameSideDataTypeFrameData3dReferenceDisplays       FrameSideDataType = 30
	FrameSideDataTypeFrameDataExif                      FrameSideDataType = 31
)

func FrameAlloc() unsafe.Pointer {
	return raw.AVFrameAlloc()
}

func FrameFree(frame unsafe.Pointer) {
	raw.AVFrameFree(frame)
}

func FrameRef(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return raw.AVFrameRef(dst, src)
}

// FrameClone Create a new frame that references the same data as src. This is a shortcut for av_frame_alloc()+av_frame_ref(). /
func FrameClone(src unsafe.Pointer) unsafe.Pointer {
	return raw.AVFrameClone(src)
}

func FrameUnref(frame unsafe.Pointer) {
	raw.AVFrameUnref(frame)
}

func FrameGetBuffer(frame unsafe.Pointer, align int32) int32 {
	return raw.AVFrameGetBuffer(frame, align)
}

// FrameIsWritable Check if the frame data is writable. only if each of the underlying buffers has only one reference, namely the one stored in this frame). Return 0 otherwise. If 1 is returned the answer is valid until av_buffer_ref() is called on any of the underlying AVBufferRefs (e.g. through av_frame_ref() or directly). /
func FrameIsWritable(frame unsafe.Pointer) int32 {
	return raw.AVFrameIsWritable(frame)
}

func FrameMakeWritable(frame unsafe.Pointer) int32 {
	return raw.AVFrameMakeWritable(frame)
}
