// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.FrameCAPI         // ensure import
var _ = capi.Register       // ensure import

// Frame is the public interface for frame domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type Frame = in.Frame

type frameWrapper struct {
	ptr  unsafe.Pointer
	capi out.FrameCAPI
}

func (w *frameWrapper) Alloc() unsafe.Pointer {
	return w.capi.Alloc()
}

func (w *frameWrapper) FreePtr(frame unsafe.Pointer) {
	w.capi.FreePtr(frame)
}

func (w *frameWrapper) Unref(frame unsafe.Pointer) {
	w.capi.Unref(frame)
}

func (w *frameWrapper) Ref(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return w.capi.Ref(dst, src)
}

func (w *frameWrapper) Clone(src unsafe.Pointer) unsafe.Pointer {
	return w.capi.Clone(src)
}

func (w *frameWrapper) GetBuffer(frame unsafe.Pointer, align int32) int32 {
	return w.capi.GetBuffer(frame, align)
}

func (w *frameWrapper) IsWritable(frame unsafe.Pointer) int32 {
	return w.capi.IsWritable(frame)
}

func (w *frameWrapper) MakeWritable(frame unsafe.Pointer) int32 {
	return w.capi.MakeWritable(frame)
}

func (w *frameWrapper) Free() {
	if w.ptr != nil {
		w.ptr = nil
	}
}

func (w *frameWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
