// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	portout "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ portout.HWAccelCAPI   // ensure import
var _ = capi.Register       // ensure import
// hwaccel domain — free functions (no wrapper type).

func DeviceCtxCreate(deviceCtx unsafe.Pointer, type_ int32, device *byte, opts unsafe.Pointer, flags int32) int32 {
	return defaultHWAccel().DeviceCtxCreate(deviceCtx, type_, device, opts, flags)
}

func FindTypeByName(name *byte) int32 {
	return defaultHWAccel().FindTypeByName(name)
}

func FrameTransferData(dst unsafe.Pointer, src unsafe.Pointer, flags int32) int32 {
	return defaultHWAccel().FrameTransferData(dst, src, flags)
}

func IterateTypes(prev int32) int32 {
	return defaultHWAccel().IterateTypes(prev)
}
