// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// ImageGetBufferSize Return the size in bytes of the amount of data required to store an image with the given parameters. /
func ImageGetBufferSize(pixFmt int32, width int32, height int32, align int32) int32 {
	return raw.AVImageGetBufferSize(pixFmt, width, height, align)
}
