// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"sync"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	"github.com/bnema/purego-ffmpeg/internal/loader"
	portout "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

// Option configures Init.
type Option = loader.Option

// SOVersions specifies SO major version numbers.
type SOVersions = loader.SOVersions

// WithDir sets the directory to search for FFmpeg shared libraries.
func WithDir(dir string) Option { return loader.WithDir(dir) }

// WithSOVersions overrides the default SO version numbers.
func WithSOVersions(v SOVersions) Option { return loader.WithSOVersions(v) }

var (
	initOnce sync.Once
	initErr  error
	adapters capi.Adapters
)

// Init loads FFmpeg libraries and wires all adapters.
// Init runs only once; subsequent calls return the cached result,
// even with different options.
func Init(opts ...Option) error {
	initOnce.Do(func() {
		handles, err := loader.Load(opts...)
		if err != nil {
			initErr = err
			return
		}
		capi.Register(capi.Handles(handles))
		adapters = capi.NewAdapters()
		core.Strerror = adapters.Util.Strerror
	})
	return initErr
}

// Shutdown performs global cleanup. Currently a no-op — FFmpeg library
// handles are released when the process exits. Reserved for future use.
func Shutdown() {}

func defaultFormat() portout.FormatCAPI {
	if adapters.Format == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Format
}

func defaultCodec() portout.CodecCAPI {
	if adapters.Codec == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Codec
}

func defaultPacket() portout.PacketCAPI {
	if adapters.Packet == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Packet
}

func defaultFrame() portout.FrameCAPI {
	if adapters.Frame == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Frame
}

func defaultSwscale() portout.SwscaleCAPI {
	if adapters.Swscale == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Swscale
}

func defaultSwresample() portout.SwresampleCAPI {
	if adapters.Swresample == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Swresample
}

func defaultDict() portout.DictCAPI {
	if adapters.Dict == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Dict
}

func defaultUtil() portout.UtilCAPI {
	if adapters.Util == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Util
}

func defaultHWAccel() portout.HWAccelCAPI {
	if adapters.HWAccel == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.HWAccel
}

func defaultStream() portout.StreamCAPI {
	if adapters.Stream == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Stream
}

func defaultFilter() portout.FilterCAPI {
	if adapters.Filter == nil {
		panic("ffmpeg: Init() must be called before using FFmpeg functions")
	}
	return adapters.Filter
}
