// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"sync"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	"github.com/bnema/purego-ffmpeg/internal/loader"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

// Option configures Init.
type Option = loader.Option

// SOVersions specifies SO major version numbers.
type SOVersions = loader.SOVersions

// WithDir sets the directory to search for FFmpeg shared libraries.
func WithDir(dir string) Option { return loader.WithDir(dir) }

// WithSOVersions overrides the default SO version numbers.
func WithSOVersions(v SOVersions) Option { return loader.WithSOVersions(v) }

var (
	initOnce sync.Once
	initErr  error
	adapters capi.Adapters
)

// Init loads FFmpeg libraries and wires all adapters.
func Init(opts ...Option) error {
	initOnce.Do(func() {
		handles, err := loader.Load(opts...)
		if err != nil {
			initErr = err
			return
		}
		capi.Register(capi.Handles(handles))
		adapters = capi.NewAdapters()
		core.Strerror = adapters.Util.Strerror
	})
	return initErr
}

// Shutdown performs global cleanup.
func Shutdown() {}

func defaultFormat() out.FormatCAPI { return adapters.Format }

func defaultCodec() out.CodecCAPI { return adapters.Codec }

func defaultPacket() out.PacketCAPI { return adapters.Packet }

func defaultFrame() out.FrameCAPI { return adapters.Frame }

func defaultSwscale() out.SwscaleCAPI { return adapters.Swscale }

func defaultSwresample() out.SwresampleCAPI { return adapters.Swresample }

func defaultDict() out.DictCAPI { return adapters.Dict }

func defaultUtil() out.UtilCAPI { return adapters.Util }
