// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// LogGetLevel Get the current log level /
func LogGetLevel() int32 {
	return raw.AVLogGetLevel()
}

// LogSetLevel Set the log level /
func LogSetLevel(level int32) {
	raw.AVLogSetLevel(level)
}
