// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

func RescaleQ(a int64, bq AVRational, cq AVRational) int64 {
	return raw.AVRescaleQ(a, bq, cq)
}

func RescaleQRnd(a int64, bq AVRational, cq AVRational, rnd int32) int64 {
	return raw.AVRescaleQRnd(a, bq, cq, rnd)
}
