// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

func PacketAlloc() unsafe.Pointer {
	return raw.AVPacketAlloc()
}

func PacketFree(pkt unsafe.Pointer) {
	raw.AVPacketFree(pkt)
}

func PacketRef(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return raw.AVPacketRef(dst, src)
}

func PacketUnref(pkt unsafe.Pointer) {
	raw.AVPacketUnref(pkt)
}

// PacketRescaleTs Convert valid timing fields (timestamps / durations) in a packet from one timebase to another. Timestamps with unknown values (AV_NOPTS_VALUE) will be ignored. expressed converted /
func PacketRescaleTs(pkt unsafe.Pointer, tbSrc AVRational, tbDst AVRational) {
	raw.AVPacketRescaleTs(pkt, tbSrc, tbDst)
}
