// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.PacketCAPI        // ensure import
var _ = capi.Register       // ensure import

// Packet is the public interface for packet domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type Packet = in.Packet

type packetWrapper struct {
	ptr  unsafe.Pointer
	capi out.PacketCAPI
}

func (w *packetWrapper) Alloc() unsafe.Pointer {
	return w.capi.Alloc()
}

func (w *packetWrapper) FreePtr(pkt unsafe.Pointer) {
	w.capi.FreePtr(pkt)
}

func (w *packetWrapper) Unref(pkt unsafe.Pointer) {
	w.capi.Unref(pkt)
}

func (w *packetWrapper) Ref(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return w.capi.Ref(dst, src)
}

func (w *packetWrapper) RescaleTs(pkt unsafe.Pointer, tbSrc AVRational, tbDst AVRational) {
	w.capi.RescaleTs(pkt, tbSrc, tbDst)
}

func (w *packetWrapper) Free() {
	if w.ptr != nil {
		w.ptr = nil
	}
}

func (w *packetWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
