// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	portin "github.com/bnema/purego-ffmpeg/internal/ports/in"
	portout "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ portout.PacketCAPI    // ensure import
var _ = capi.Register       // ensure import

// Packet is the public interface for packet domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type Packet = portin.Packet

// Compile-time interface satisfaction check.
var _ Packet = (*packetWrapper)(nil)

type packetWrapper struct {
	ptr  unsafe.Pointer
	capi portout.PacketCAPI
}

// NewPacketWithPtr wraps an existing pointer with Packet methods.
func NewPacketWithPtr(ptr unsafe.Pointer) *packetWrapper {
	return &packetWrapper{ptr: ptr, capi: defaultPacket()}
}

// AllocPacket allocates and returns a new Packet.
// Unlike the raw Alloc() method, this stores the pointer internally.
// Returns nil if the C allocation fails.
func AllocPacket() *packetWrapper {
	w := &packetWrapper{capi: defaultPacket()}
	w.ptr = w.capi.Alloc()
	if w.ptr == nil {
		return nil
	}
	return w
}

func (w *packetWrapper) Alloc() unsafe.Pointer {
	return w.capi.Alloc()
}

func (w *packetWrapper) FreePtr(pkt unsafe.Pointer) {
	w.capi.FreePtr(pkt)
}

func (w *packetWrapper) Unref(pkt unsafe.Pointer) {
	w.capi.Unref(pkt)
}

func (w *packetWrapper) Ref(dst unsafe.Pointer, src unsafe.Pointer) int32 {
	return w.capi.Ref(dst, src)
}

func (w *packetWrapper) RescaleTs(pkt unsafe.Pointer, tbSrc AVRational, tbDst AVRational) {
	w.capi.RescaleTs(pkt, tbSrc, tbDst)
}

func (w *packetWrapper) Free() {
	if w.ptr != nil {
		// NOTE: Some FFmpeg free functions (avcodec_free_context, av_packet_free,
		// av_frame_free, swr_free) take double pointers (Type**) in C. The purego
		// binding passes a single pointer. The C function may attempt to NULL the
		// caller's pointer, but since we nil w.ptr on the Go side, this is safe
		// for single-call usage. Do not call Free() concurrently.
		w.capi.FreePtr(w.ptr)
		w.ptr = nil
	}
}

// Ptr returns the raw C pointer. The returned pointer becomes invalid
// after Free() is called. Do not retain it across Free() calls.
func (w *packetWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
