// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// Rational Rational number (pair of numerator and denominator). /
type Rational struct {
	ptr *raw.AVRational
}

func (w *Rational) Raw() unsafe.Pointer {
	if w == nil {
		return nil
	}
	return unsafe.Pointer(w.ptr)
}

func (w *Rational) Num() int32 {
	return w.ptr.Num
}

func (w *Rational) Den() int32 {
	return w.ptr.Den
}
