// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// SampleFormat Audio sample formats - The data described by the sample format is always in native-endian order. Sample values can be expressed by native C types, hence the lack of a signed 24-bit sample format even though it is a common raw audio data format. - The floating-point formats are based on full volume being in the range [-1.0, 1.0]. Any values outside this range are beyond full volume level. - The data layout as used in av_samples_fill_arrays() and elsewhere in FFmpeg (such as AVFrame in libavcodec) is as follows: For planar sample formats, each audio channel is in a separate data plane, and linesize is the buffer size, in bytes, for a single plane. All data planes must be the same size. For packed sample formats, only the first data plane is used, and samples for each channel are interleaved. In this case, linesize is the buffer size, in bytes, for the 1 plane. /
type SampleFormat int32

const (
	SampleFormatSampleFmtNone SampleFormat = -1
	SampleFormatSampleFmtU8   SampleFormat = 0
	SampleFormatSampleFmtS16  SampleFormat = 1
	SampleFormatSampleFmtS32  SampleFormat = 2
	SampleFormatSampleFmtFlt  SampleFormat = 3
	SampleFormatSampleFmtDbl  SampleFormat = 4
	SampleFormatSampleFmtU8p  SampleFormat = 5
	SampleFormatSampleFmtS16p SampleFormat = 6
	SampleFormatSampleFmtS32p SampleFormat = 7
	SampleFormatSampleFmtFltp SampleFormat = 8
	SampleFormatSampleFmtDblp SampleFormat = 9
	SampleFormatSampleFmtS64  SampleFormat = 10
	SampleFormatSampleFmtS64p SampleFormat = 11
	SampleFormatSampleFmtNb   SampleFormat = 12
)

// GetSampleFmtName Return the name of sample_fmt, or NULL if sample_fmt is not recognized. /
func GetSampleFmtName(sampleFmt int32) string {
	ret := raw.AVGetSampleFmtName(sampleFmt)
	return goString(ret)
}

// GetBytesPerSample Return number of bytes per sample. sample format /
func GetBytesPerSample(sampleFmt int32) int32 {
	return raw.AVGetBytesPerSample(sampleFmt)
}

// SampleFmtIsPlanar Check if the sample format is planar. /
func SampleFmtIsPlanar(sampleFmt int32) int32 {
	return raw.AVSampleFmtIsPlanar(sampleFmt)
}
