// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

type SampleFormat int32

const (
	SampleFormatSampleFmtNone SampleFormat = -1
	SampleFormatSampleFmtU8   SampleFormat = 0
	SampleFormatSampleFmtS16  SampleFormat = 1
	SampleFormatSampleFmtS32  SampleFormat = 2
	SampleFormatSampleFmtFlt  SampleFormat = 3
	SampleFormatSampleFmtDbl  SampleFormat = 4
	SampleFormatSampleFmtU8p  SampleFormat = 5
	SampleFormatSampleFmtS16p SampleFormat = 6
	SampleFormatSampleFmtS32p SampleFormat = 7
	SampleFormatSampleFmtFltp SampleFormat = 8
	SampleFormatSampleFmtDblp SampleFormat = 9
	SampleFormatSampleFmtS64  SampleFormat = 10
	SampleFormatSampleFmtS64p SampleFormat = 11
	SampleFormatSampleFmtNb   SampleFormat = 12
)

// GetSampleFmtName Return the name of sample_fmt, or NULL if sample_fmt is not recognized. /
func GetSampleFmtName(sampleFmt int32) string {
	ret := raw.AVGetSampleFmtName(sampleFmt)
	return goString(ret)
}

// GetBytesPerSample Return number of bytes per sample. sample format /
func GetBytesPerSample(sampleFmt int32) int32 {
	return raw.AVGetBytesPerSample(sampleFmt)
}

// SampleFmtIsPlanar Check if the sample format is planar. /
func SampleFmtIsPlanar(sampleFmt int32) int32 {
	return raw.AVSampleFmtIsPlanar(sampleFmt)
}
