// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.StreamCAPI        // ensure import
var _ = capi.Register       // ensure import

// Stream is the public interface for stream domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type Stream = in.Stream

type streamWrapper struct {
	ptr  unsafe.Pointer
	capi out.StreamCAPI
}

// NewStreamWithPtr wraps an existing pointer with Stream methods.
func NewStreamWithPtr(ptr unsafe.Pointer) *streamWrapper {
	return &streamWrapper{ptr: ptr, capi: defaultStream()}
}

func (w *streamWrapper) Index() int32 {
	if w.ptr == nil {
		var zero int32
		return zero
	}
	return *(*int32)(unsafe.Add(w.ptr, capi.OffsetAVStreamIndex))
}

func (w *streamWrapper) CodecParameters() unsafe.Pointer {
	if w.ptr == nil {
		var zero unsafe.Pointer
		return zero
	}
	return *(*unsafe.Pointer)(unsafe.Add(w.ptr, capi.OffsetAVStreamCodecParameters))
}

func (w *streamWrapper) TimeBase() AVRational {
	if w.ptr == nil {
		var zero AVRational
		return zero
	}
	return *(*AVRational)(unsafe.Add(w.ptr, capi.OffsetAVStreamTimeBase))
}

func (w *streamWrapper) SetTimeBase(v AVRational) {
	if w.ptr == nil {
		return
	}
	*(*AVRational)(unsafe.Add(w.ptr, capi.OffsetAVStreamTimeBase)) = v
}

func (w *streamWrapper) Duration() int64 {
	if w.ptr == nil {
		var zero int64
		return zero
	}
	return *(*int64)(unsafe.Add(w.ptr, capi.OffsetAVStreamDuration))
}

func (w *streamWrapper) NbFrames() int64 {
	if w.ptr == nil {
		var zero int64
		return zero
	}
	return *(*int64)(unsafe.Add(w.ptr, capi.OffsetAVStreamNbFrames))
}

func (w *streamWrapper) Free() {
	if w.ptr != nil {
		w.ptr = nil
	}
}

func (w *streamWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
