// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.SwresampleCAPI    // ensure import
var _ = capi.Register       // ensure import

// SwresampleContext is the public interface for swresample domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type SwresampleContext = in.SwresampleContext

type swresampleWrapper struct {
	ptr  unsafe.Pointer
	capi out.SwresampleCAPI
}

func (w *swresampleWrapper) Alloc() unsafe.Pointer {
	return w.capi.Alloc()
}

func (w *swresampleWrapper) Init(s unsafe.Pointer) int32 {
	return w.capi.Init(s)
}

func (w *swresampleWrapper) Convert(s unsafe.Pointer, out unsafe.Pointer, outCount int32, in unsafe.Pointer, inCount int32) int32 {
	return w.capi.Convert(s, out, outCount, in, inCount)
}

func (w *swresampleWrapper) FreePtr(s unsafe.Pointer) {
	w.capi.FreePtr(s)
}

func (w *swresampleWrapper) Free() {
	if w.ptr != nil {
		w.capi.FreePtr(w.ptr)
		w.ptr = nil
	}
}

func (w *swresampleWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
