// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

func SwrAlloc() unsafe.Pointer {
	return raw.SWRAlloc()
}

func SwrInit(s unsafe.Pointer) int32 {
	return raw.SWRInit(s)
}

func SwrFree(s unsafe.Pointer) {
	raw.SWRFree(s)
}

func SwrConvert(s unsafe.Pointer, out unsafe.Pointer, outCount int32, in unsafe.Pointer, inCount int32) int32 {
	return raw.SWRConvert(s, out, outCount, in, inCount)
}

// SwresampleVersion Return the @ref LIBSWRESAMPLE_VERSION_INT constant. This is useful to check if the build-time libswresample has the same version as the run-time one. /
func SwresampleVersion() uint32 {
	return raw.SwresampleVersion()
}
