// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	portin "github.com/bnema/purego-ffmpeg/internal/ports/in"
	portout "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil)  // ensure import
var _ = core.CheckError      // ensure import
var _ portout.SwresampleCAPI // ensure import
var _ = capi.Register        // ensure import

// SwresampleContext is the public interface for swresample domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type SwresampleContext = portin.SwresampleContext

type swresampleWrapper struct {
	ptr  unsafe.Pointer
	capi portout.SwresampleCAPI
}

// NewSwresampleContextWithPtr wraps an existing pointer with SwresampleContext methods.
func NewSwresampleContextWithPtr(ptr unsafe.Pointer) *swresampleWrapper {
	return &swresampleWrapper{ptr: ptr, capi: defaultSwresample()}
}

// AllocSwresampleContext allocates and returns a new SwresampleContext.
// Unlike the raw Alloc() method, this stores the pointer internally.
// Returns nil if the C allocation fails.
func AllocSwresampleContext() *swresampleWrapper {
	w := &swresampleWrapper{capi: defaultSwresample()}
	w.ptr = w.capi.Alloc()
	if w.ptr == nil {
		return nil
	}
	return w
}

func (w *swresampleWrapper) Alloc() unsafe.Pointer {
	return w.capi.Alloc()
}

func (w *swresampleWrapper) Init(s unsafe.Pointer) int32 {
	return w.capi.Init(s)
}

func (w *swresampleWrapper) Convert(s unsafe.Pointer, out unsafe.Pointer, outCount int32, in unsafe.Pointer, inCount int32) int32 {
	return w.capi.Convert(s, out, outCount, in, inCount)
}

func (w *swresampleWrapper) FreePtr(s unsafe.Pointer) {
	w.capi.FreePtr(s)
}

func (w *swresampleWrapper) Free() {
	if w.ptr != nil {
		// NOTE: Some FFmpeg free functions (avcodec_free_context, av_packet_free,
		// av_frame_free, swr_free) take double pointers (Type**) in C. The purego
		// binding passes a single pointer. The C function may attempt to NULL the
		// caller's pointer, but since we nil w.ptr on the Go side, this is safe
		// for single-call usage. Do not call Free() concurrently.
		w.capi.FreePtr(w.ptr)
		w.ptr = nil
	}
}

func (w *swresampleWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
