// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/ffmpeg/internal/raw"
)

// SwscaleVersion Color conversion and scaling library. Return the LIBSWSCALE_VERSION_INT constant. /
func SwscaleVersion() uint32 {
	return raw.SwscaleVersion()
}

// SwsFreeContext Free the swscaler context swsContext. If swsContext is NULL, then does nothing. /
func SwsFreeContext(swscontext unsafe.Pointer) {
	raw.SWSFreeContext(swscontext)
}

// SwsGetContext Allocate and return an SwsContext. You need it to perform scaling/conversion operations using sws_scale(). For SWS_BICUBIC param[0] and [1] tune the shape of the basis function, param[0] tunes f(1) and param[1] f´(1) For SWS_GAUSS param[0] tunes the exponent and thus cutoff frequency For SWS_LANCZOS param[0] tunes the width of the window function written /
func SwsGetContext(srcw int32, srch int32, srcformat int32, dstw int32, dsth int32, dstformat int32, flags int32, srcfilter unsafe.Pointer, dstfilter unsafe.Pointer, param unsafe.Pointer) unsafe.Pointer {
	return raw.SWSGetContext(srcw, srch, srcformat, dstw, dsth, dstformat, flags, srcfilter, dstfilter, param)
}

func SwsScale(c unsafe.Pointer, srcslice unsafe.Pointer, srcstride int32, srcslicey int32, srcsliceh int32, dst unsafe.Pointer, dststride int32) int32 {
	return raw.SWSScale(c, srcslice, srcstride, srcslicey, srcsliceh, dst, dststride)
}
