// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	in "github.com/bnema/purego-ffmpeg/internal/ports/in"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.SwscaleCAPI       // ensure import
var _ = capi.Register       // ensure import

// SwscaleContext is the public interface for swscale domain operations.
// Re-exported from internal/ports/in for consumer convenience.
type SwscaleContext = in.SwscaleContext

type swscaleWrapper struct {
	ptr  unsafe.Pointer
	capi out.SwscaleCAPI
}

// NewSwscaleContextWithPtr wraps an existing pointer with SwscaleContext methods.
func NewSwscaleContextWithPtr(ptr unsafe.Pointer) *swscaleWrapper {
	return &swscaleWrapper{ptr: ptr, capi: defaultSwscale()}
}

func (w *swscaleWrapper) GetContext(srcw int32, srch int32, srcformat int32, dstw int32, dsth int32, dstformat int32, flags int32, srcfilter unsafe.Pointer, dstfilter unsafe.Pointer, param unsafe.Pointer) unsafe.Pointer {
	return w.capi.GetContext(srcw, srch, srcformat, dstw, dsth, dstformat, flags, srcfilter, dstfilter, param)
}

func (w *swscaleWrapper) Scale(c unsafe.Pointer, srcslice unsafe.Pointer, srcstride int32, srcslicey int32, srcsliceh int32, dst unsafe.Pointer, dststride int32) int32 {
	return w.capi.Scale(c, srcslice, srcstride, srcslicey, srcsliceh, dst, dststride)
}

func (w *swscaleWrapper) FreeContext(swscontext unsafe.Pointer) {
	w.capi.FreeContext(swscontext)
}

func (w *swscaleWrapper) Free() {
	if w.ptr != nil {
		w.capi.FreeContext(w.ptr)
		w.ptr = nil
	}
}

func (w *swscaleWrapper) Ptr() unsafe.Pointer {
	return w.ptr
}
