// Code generated by ffmpeggen. DO NOT EDIT.

package ffmpeg

import (
	"unsafe"

	"github.com/bnema/purego-ffmpeg/internal/capi"
	"github.com/bnema/purego-ffmpeg/internal/core"
	out "github.com/bnema/purego-ffmpeg/internal/ports/out"
)

var _ = unsafe.Pointer(nil) // ensure import
var _ = core.CheckError     // ensure import
var _ out.UtilCAPI          // ensure import
var _ = capi.Register       // ensure import
// util domain — free functions (no wrapper type).

func Malloc(size uintptr) unsafe.Pointer {
	return defaultUtil().Malloc(size)
}

func Free(ptr unsafe.Pointer) {
	defaultUtil().Free(ptr)
}

func OptSet(obj unsafe.Pointer, name *byte, val *byte, searchFlags int32) int32 {
	return defaultUtil().OptSet(obj, name, val, searchFlags)
}

func OptSetInt(obj unsafe.Pointer, name *byte, val int64, searchFlags int32) int32 {
	return defaultUtil().OptSetInt(obj, name, val, searchFlags)
}

func LogSetLevel(level int32) {
	defaultUtil().LogSetLevel(level)
}

func LogGetLevel() int32 {
	return defaultUtil().LogGetLevel()
}

func RescaleQ(a int64, bq AVRational, cq AVRational) int64 {
	return defaultUtil().RescaleQ(a, bq, cq)
}

func ImageGetBufferSize(pixFmt int32, width int32, height int32, align int32) int32 {
	return defaultUtil().ImageGetBufferSize(pixFmt, width, height, align)
}

func Strerror(errnum int32, errbuf *byte, errbufSize uintptr) int32 {
	return defaultUtil().Strerror(errnum, errbuf, errbufSize)
}
